-- HUS Dashboard — `tasks` table: Supabase as single source of truth.
-- Run ONCE in the Supabase SQL editor for the hus-dashboard project.
--
-- Why: the frontend used to read a frozen, build-time copy of tasks.json and
-- only overlay status changes from `task_status`. New tasks added via MCP could
-- never appear, and cleanup never reflected. This table holds the FULL task
-- rows so MCP writes and frontend edits share one live source.
--
-- Generated by scripts/gen_tasks_seed.py — do not hand-edit the seed block.

create table if not exists tasks (
  id              text primary key,
  task            text,
  project         text,
  priority        text,
  owner           text,
  due_date        text,                       -- 'YYYY-MM-DD' or '' (matches tasks.json)
  pdca            text,
  pdca_updated_at text,
  status          text,
  notes           text,
  completed_at    text,
  deleted         boolean      not null default false,
  updated_at      timestamptz  not null default now()
);

alter table tasks enable row level security;

-- The dashboard uses the public anon key; RLS is what protects the data.
drop policy if exists "anon read tasks"   on tasks;
drop policy if exists "anon write tasks"  on tasks;
drop policy if exists "anon update tasks" on tasks;
create policy "anon read tasks"   on tasks for select to anon using (true);
create policy "anon write tasks"  on tasks for insert to anon with check (true);
create policy "anon update tasks" on tasks for update to anon using (true) with check (true);

-- ── Seed: current board state (tasks.json + live task_status overlay) ──
insert into tasks (id, task, project, priority, owner, due_date, pdca, pdca_updated_at, status, notes, completed_at) values
  ('task-018', 'Add reimbursement to ShipFare #7859', 'proj-010', 'medium', 'Tad', '2026-04-03', 'Plan', '2026-03-29', 'done', NULL, '2026-04-28'),
  ('task-1774876173033', '⚠️ [Follow-up] Respond to DropShip with CVR & cart funnel progress report, schedule meetings April 10 & April 20 — due today, High', 'proj-001', 'medium', NULL, NULL, 'Act', '2026-03-30', 'done', 'Follow-up added 2026-03-30 via MCP', '2026-04-02'),
  ('task-1775000001', 'Follow up B2B sales with Sam', 'proj-009', 'high', 'Tad', '2026-03-30', 'Act', '2026-04-02', 'done', NULL, '2026-04-02'),
  ('task-1775000002', 'ETA check for London trip', 'proj-006', 'high', 'Tad', '2026-03-30', 'Act', '2026-04-02', 'done', NULL, '2026-04-02'),
  ('task-1775000003', 'Update credit card authorization form', 'proj-010', 'high', 'Tad', '2026-03-30', 'Act', '2026-04-02', 'done', NULL, '2026-04-02'),
  ('task-1775000004', 'Fix UK product price list', 'proj-006', 'high', 'Tad', '2026-03-30', 'Act', '2026-04-26', 'done', NULL, '2026-04-02'),
  ('task-1775000005', 'Invoice collection from Japan — confirm with Mitsuki', 'proj-010', 'high', 'Tad', '2026-03-30', 'Act', '2026-04-02', 'done', NULL, '2026-04-02'),
  ('task-1775000006', 'SNS post — big anago just arrived', 'proj-010', 'low', 'Tad', '2026-03-31', 'Act', '2026-04-26', 'done', NULL, '2026-04-02'),
  ('task-1775000007', 'Check in Swiss Air and Hilton Hotel for tomorrow', 'proj-009', 'high', 'Tad', '2026-03-30', 'Act', '2026-04-02', 'done', NULL, '2026-04-02'),
  ('task-1775000008', 'Respond to all customer inquiries', 'proj-010', 'high', 'Tad', '2026-03-30', 'Plan', '2026-03-30', 'done', NULL, '2026-04-02'),
  ('task-1775206943524', '⚠️ [Follow-up] Vercel Pro plan payment — April 9. Make full use of $20/month: enable Analytics, Speed Insights, custom domain.', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-03', 'not-started', 'Follow-up added 2026-04-03 via MCP', NULL),
  ('task-1775214009995', '⚠️ [Follow-up] 帆立バイヤーへ英語オファーシート送付 → 返答次第でPO確保へ動く', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-03', 'not-started', 'Follow-up added 2026-04-03 via MCP', NULL),
  ('task-1775386027056', '⚠️ [Follow-up] Mailchimp — Vercelに MAILCHIMP_API_KEY + MAILCHIMP_LIST_ID を追加してダッシュボード連携を有効化（ナランチャへ）', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-05', 'not-started', 'Follow-up added 2026-04-05 via MCP', NULL),
  ('task-1775424535628', 'CVR改善進捗アップデート 2026-04-05', 'proj-001', 'medium', NULL, NULL, 'Plan', '2026-04-05', 'done', NULL, '2026-04-28'),
  ('task-1775524189090', '水曜4/8 DropShipレポート受領確認して小池に即報告', 'proj-010', 'high', 'とべぶた', '2026-04-08', 'Act', '2026-04-22', 'done', NULL, '2026-04-22'),
  ('task-1775524762400', 'モバイルスティッキーATC実装 main-product.liquidに追加', 'proj-010', 'high', 'とべぶた', '2026-04-08', 'Act', '2026-04-22', 'done', NULL, '2026-04-22'),
  ('task-1775524768830', 'MIDA Survey設置 カート離脱理由を直接聞く', 'proj-010', 'high', 'とべぶた', '2026-04-08', 'Do', '2026-04-07', 'done', NULL, '2026-04-25'),
  ('task-1775555853067', 'UK product price list 作成', 'proj-006', 'low', 'Tad', NULL, 'Plan', '2026-04-07', 'blocked', 'Tad判断でHold。再開タイミングはTad指示待ち。', NULL),
  ('task-1775555900181', 'スイス会社設立準備', NULL, 'high', 'Tad', '2026-04-07', 'Plan', '2026-04-07', 'done', NULL, '2026-04-25'),
  ('task-1775570663492', '【週次ルーティン】鮮魚部隊SKUレポート確認 → 戦略判断', NULL, 'medium', '小池', NULL, 'Check', '2026-04-07', 'not-started', '毎週月曜。売れ筋TOP3・粗利割れSKU・価格変動・供給リスク・戦略提言の5点を鮮魚部隊から受領し、小池がTadに戦略を上げる。B2B粗利27%実額・B2C粗利45%平均が基準。', NULL),
  ('task-1775576043569', '新商品追加 → Shopify登録（セット商品＋鮮魚フィレ）', 'proj-010', 'high', 'Tad', '2026-04-07', 'Do', '2026-04-07', 'done', '山幸マグロさくセット・和牛セット・手巻きセット・抹茶ほうじ茶セット・鮮魚冷凍フィレ＆ドレス・他鮮魚関連', '2026-04-25'),
  ('task-1775576047536', 'Mailchimp配信 — 新商品アナウンス', 'proj-010', 'high', '脳汁', '2026-04-07', 'Do', '2026-04-07', 'done', '新商品追加完了後に配信。対象リスト・件名・本文を脳汁が用意。', '2026-04-28'),
  ('task-1775634150751', 'B2B請求書送付 — 水曜・土曜朝（週次ルーティン）', 'proj-009', 'high', 'Tad', NULL, 'Do', '2026-04-08', 'done', '毎週水曜・土曜の朝にB2B顧客へ請求書を送付。現在は手動。将来的にFreshline or Shopify連携で自動化予定。', '2026-05-11'),
  ('task-1775634155453', '⚠️ [Follow-up] B2B請求書送付の自動化を検討 — Freshline API or Shopify連携。ナランチャに実現可能性を調査させる。', 'proj-009', 'medium', NULL, NULL, 'Act', '2026-04-08', 'not-started', 'Follow-up added 2026-04-08 via MCP', NULL),
  ('task-1775634606364', 'Vercel Pro 支払い設定（期限4/11）+ Analytics・Speed Insights有効化', 'proj-010', 'high', 'Tad', '2026-04-09', 'Act', '2026-04-22', 'done', 'トライアル残り3日（4/11期限）。支払い設定 + Analytics・Speed Insights有効化・カスタムドメイン設定まで一気にやる。', '2026-04-22'),
  ('task-1775644021450', '4/10 DropShipミーティング — アジェンダ準備完了', 'proj-010', 'high', 'Tad', '2026-04-10', 'Act', '2026-04-22', 'done', NULL, '2026-04-22'),
  ('task-1775728282572', '⚠️ [Follow-up] UK Hamamchi案件：50/50。担当者からの次のアクション待ち。進展があり次第Tadに報告。', 'proj-003', 'medium', NULL, NULL, 'Act', '2026-04-09', 'not-started', 'Follow-up added 2026-04-09 via MCP', NULL),
  ('task-1775758960537', 'Shopify Agentic Storefronts 有効化 + Knowledge Base App設置', 'proj-010', 'high', 'ナランチャ', '2026-04-10', 'Act', '2026-04-25', 'done', 'Shopify Admin → Settings → Sales Channels → Agentic Storefronts確認・有効化。Knowledge Base Appインストール。CAC削減・新チャネル獲得が目的。', '2026-04-25'),
  ('task-1776096128223', 'ダッシュボードデザイン全面更新（DM Sans・新カラーパレット）', 'proj-010', 'high', 'ナランチャ', '2026-04-14', 'Act', '2026-04-22', 'done', 'DM Sans + DM Mono、#f5f4f0背景、カード12px角丸、4列メトリクス、sticky topbar。完了条件はVercelデプロイ後の画面キャプチャ報告。', '2026-04-22'),
  ('task-1776096139040', 'SKU管理機能 仕様設計（Jus → ナランチャへ引き渡し）', 'proj-010', 'high', 'Jus', NULL, 'Plan', '2026-04-13', 'not-started', 'ナランチャからGitHubアクセス取得後、コードベース確認→機能設計→小池に提出。実装はナランチャ担当。優先順位：①粗利自動計算②価格変動アラート③月曜定例レポート自動生成。', NULL),
  ('task-1776124468369', 'Yamayuki Tuna Set — Compare-at price・Tags・URL handle 完成', 'proj-010', 'high', 'Les yeux', '2026-04-14', 'Do', '2026-04-13', 'done', 'Compare-at price入力・Tags追加・URL handle変更の3点が未完了。完成してからTadに確認を取ること。', '2026-04-28'),
  ('task-1776286829321', 'Supabase Pro確認済 — hus-dashboardプロジェクト自動停止リスク解消 ($25/月)', NULL, 'low', NULL, NULL, 'Act', '2026-04-15', 'done', '2026-04-15時点でPro (Current plan)確認済。自動停止なし。GitHubトークン(HUS Deploy)も同日再生成済。', '2026-04-15'),
  ('task-1776364754820', 'B2B インボイス作成・送付（水曜定例）', 'proj-009', 'high', '疾風', '2026-04-15', 'Do', '2026-04-16', 'done', NULL, '2026-04-28'),
  ('task-1776364759226', 'Mother''s Day Mailchimpキャンペーン完成・Tadに確認→配信', 'proj-010', 'high', '脳汁', '2026-04-15', 'Do', '2026-04-16', 'done', NULL, '2026-04-28'),
  ('task-1776364764807', 'まどろむ 注文処理', 'proj-009', 'high', 'Tad', '2026-04-15', 'Do', '2026-04-16', 'done', NULL, '2026-04-28'),
  ('task-1776364770369', '4月30日集荷アレンジ', 'proj-009', 'high', '疾風', '2026-04-15', 'Do', '2026-04-16', 'done', '4月30日集荷に向けてサプライヤー・ShipFareとの調整。', '2026-04-28'),
  ('task-1776672507654', '⚠️ [Follow-up] DropShip MTG → 4/20から4/23に変更。25%OFFクーポン効果を持って臨む。契約継続判断の分岐点。', 'proj-001', 'medium', NULL, NULL, 'Act', '2026-04-20', 'not-started', 'Follow-up added 2026-04-20 via MCP', NULL),
  ('task-1776695659549', '【緊急】Vercel セキュリティインシデント対応 — 環境変数ローテーション', NULL, 'high', NULL, '2026-04-21', 'Do', '2026-04-20', 'not-started', '2026年4月のVercelセキュリティインシデント対応。①vercel.com/all-env-varsでhus-dashboardの環境変数を全確認 ②sensitiveマークのないShopifyトークン・Supabase URLなどを全ローテーション ③今後すべてのAPIキーをsensitiveとしてマーク ④vercel.com/activity-logで不審アクセス確認 ⑤デプロイ履歴に身に覚えのないものがないか確認', NULL),
  ('task-1776763982447', 'ダッシュボード「今やるべきTask」ビュー実装 — 開いた瞬間に全進捗が見える', 'proj-010', 'high', 'ナランチャ', '2026-04-22', 'Act', '2026-04-26', 'done', 'What''s upページ再設計。①今日のTOP優先タスク②プロジェクト別進捗バー③Overdue赤ハイライト④担当者別タスク。MCP経由でリアルタイム更新。完成条件：開いた瞬間に全員の進捗が一目でわかること。', '2026-04-28'),
  ('task-1776764882975', 'ダッシュボード「Team」ページ新規作成（手動編集機能付き）', 'proj-010', 'high', 'ナランチャ', '2026-04-22', 'Do', '2026-04-21', 'not-started', '全メンバーカード表示・Edit/Add機能・team.json保存・DM Sansデザイン統一・モバイル対応。完了条件：Tadが実際に編集できることを確認。', NULL),
  ('task-1776766881658', '朝ダッシュボード v2.2 ワイヤーフレーム作成', 'proj-010', 'high', 'La Main', '2026-04-25', 'Plan', '2026-04-21', 'not-started', 'v2.2仕様。5ブロック：Strategic Priorities/Revenue Command/Cash+Alerts/Today Focus/Team Pulse。静かで高級感のある操作盤。提出はスクリーンショットで小池へ。TadのGO後ナランチャへ渡す。', NULL),
  ('task-1776766886879', 'v2.2データソース調査（Shopify/Freshline/Cash）', 'proj-010', 'high', 'ナランチャ', '2026-04-23', 'Plan', '2026-04-21', 'done', 'Shopify→B2C売上自動取得可否、Freshline→B2B売上自動取得可否、Export/Broker→手動か自動か、Cash Status→QuickBooksか手動か。結果を小池に報告。', '2026-04-28'),
  ('task-1776898281387', 'Vercel Analytics・Speed Insights 有効化', 'proj-010', 'medium', 'Tad', '2026-04-25', 'Do', '2026-04-22', 'not-started', '旧タスク「Vercel Pro 支払い設定（期限4/11）+ Analytics・Speed Insights有効化」から分離。支払いはPro plan稼働により完了確認済。残務はVercel画面でAnalytics＋Speed Insightsのスイッチ有効化のみ（5分作業）。', NULL),
  ('task-1776978408338', 'Dashboard Step 6 — Data Wiring Sprint (seed脱却 + 黒要素根絶)', 'proj-010', 'high', 'ナランチャ', '2026-04-30', 'Plan', '2026-04-23', 'not-started', 'PR #2マージ後の次フェーズ。全データソースはseed/mock確認済（ナランチャレポート2026-04-23）。優先順：①C1 Revenue summary → Shopify sync JSON wiring、②C4 Team Pulse % → projects.json集計、③C3 Today Focus → tasks.json reader、④C2 Cash riskNote → Supabase。追加：黒要素根絶（ナビpill・戦略pill・What''s up?banner）。Step 6設計書をナランチャが起草→小池確認→Tad承認→着手の順。', NULL),
  ('task-1777039825103', 'CAPE/IEEPA 関税還付申請 — Sterling CHBに返信＋ACHポータル登録', NULL, 'high', NULL, '2026-04-27', 'Act', '2026-04-24', 'done', 'Sterling CHB Inc. (Peter P. Sterling / sterlingchb@sterlingchb.com / 516.216.1900) からCAPE代行オファーあり。Option 1（フルサービス$500、1-300エントリー）が最有力。①ACEポータルに銀行口座(ACH)登録: https://ace-accounts.cbp.gov/s/importer-form ②Sterlingに返信してOption選択。還付はdirect depositのみ。', '2026-04-24'),
  ('task-1777278568115', '15時EU雲丹輸出サポートMTG (4/27月)', 'proj-006', 'high', 'Tad+Pino', '2026-04-27', 'Act', '2026-04-28', 'done', 'EU雲丹輸出サポートMTG・重要案件。Tad明示「マジがんばれ」案件。MTGの参加者・目的・決定事項・成果物KPIは要追加。Pino owner継続。レポート受領後に小池が状況把握・方向性判断。', '2026-04-28'),
  ('task-1777278572007', '⚠️ [Follow-up] 15時EU MTG後 — レポート受領 → 小池状況把握 → 次アクション方向性判断 → Tadへ経営アドバイス', 'proj-006', 'medium', NULL, NULL, 'Act', '2026-04-27', 'not-started', 'Follow-up added 2026-04-27 via MCP', NULL),
  ('task-1777278608158', 'Glasgow往復航空券手配 (Personal)', NULL, 'medium', 'Tad', '2026-04-27', 'Do', '2026-04-27', 'not-started', 'Tad personal task (4/26明示)。出張記録としてFEIE 2555/1116に影響可能性あり・滞在日数を後でtrack要。', NULL),
  ('task-1777278615663', '鮮魚をHPに載せる (Shopify SKU登録・商品規定書v1.0適用)', 'proj-010', 'high', 'Tad', '2026-04-29', 'Do', '2026-04-27', 'in-progress', 'Tad明示「鮮魚をHPに載せる」(4/26)。既存overdueタスク「新商品追加→Shopify登録(セット商品+鮮魚フィレ)」と関連可能性。Shopify Liquid section + 商品規定書v1.0適用。Jus巻き込み案件か単独かTad判断要。', NULL),
  ('task-1777278623286', 'Blog執筆: Hokkaido Hakodate Hotate and Ikura', 'proj-010', 'medium', 'Tad+脳汁', '2026-05-04', 'Do', '2026-04-27', 'in-progress', 'Tad+脳汁共同作業 (4/26明示)。GEO戦略#2の最初の1本目候補。撮影日YYYY-MM-DD/地名(函館・市場名・船名)/取引先固有名詞/写真6-10枚+キャプション必須。完成前小池GEO観点review可能。', NULL),
  ('task-1777280477873', '⚠️ [Follow-up] [owner訂正] 15時EU MTG (4/27) — owner = Tad+@EUがんばれ。Pinoは別MTGまたは会社設立進捗のみ報告', 'proj-006', 'medium', NULL, NULL, 'Act', '2026-04-27', 'not-started', 'Follow-up added 2026-04-27 via MCP', NULL),
  ('task-1777296624228', 'claude.ai Projects — チーム別CLAUDE.md設定完了', NULL, 'high', NULL, NULL, 'Act', '2026-04-27', 'done', '8チーム全員のProjectをclaude.aiに作成・Instructions設定完了。ナランチャ/脳汁/疾風/Jus/とべぶた/La Main/Les Yeux/EUがんばれ。今後はチーム作業はブラウザのProjectで、MCP連携はClaude Desktopで運用。', '2026-04-27'),
  ('task-1777298788157', '【La Main承認待ち】アクセントカラー Sakura Salmon への移行', NULL, 'medium', NULL, NULL, 'Plan', '2026-04-27', 'not-started', 'La Main提案: --accent-primary #E89A8A / --accent-deep #C8604F / --accent-pale #F5C9BF。対象: HUS Dashboard・商品規格書・Tuna Show（Toro Red維持）。Tad承認後にナランチャが実装。CSS変数1箇所差し替えで完結。', NULL),
  ('task-1777372497702', 'Mailchimp Mother''s Day campaign フォローアップ', 'proj-010', 'high', 'Tad+とべぶた', '2026-04-27', 'Act', '2026-04-28', 'done', 'Tad-とべぶた連携。Mailchimp Mother''s Day Email 1/2/3配信のフォローアップ。Open率・CTR・Revenue確認・5/2 cutoffまでの目標$5,000進捗追跡。とべぶた専任CVR領域なので小池非介入・Tadは状況確認とdecisionのみ。', '2026-04-30'),
  ('task-1777372504598', 'Glasgow航空券手配 (Personal)', NULL, 'medium', 'Tad', '2026-04-27', 'Do', '2026-04-28', 'in-progress', 'Tad personal task (4/26明示・継続)。出張記録としてFEIE 2555/1116への影響可能性あり。Glasgow滞在日数を後で確定後に米国非居住日数2025との関係をtrack要。', NULL),
  ('task-1777372509879', 'Order to FICI', NULL, 'high', 'Tad', '2026-04-27', 'Do', '2026-04-28', 'in-progress', 'FICI = ゼンヤクノー鵜戸口さんのFDA登録経路で過去言及あり。発注内容・数量・送付先を後で要確認。FDA番号取得の進捗にも関連する可能性。', NULL),
  ('task-1777372516861', 'Cost analysis + P&L review with CFO', NULL, 'high', 'Tad+CFO', '2026-04-27', 'Check', '2026-04-28', 'in-progress', 'CFO同席のコスト分析+P&Lレビュー。経営判断の核心ミーティング。Q1/Q2の財務状況確認・Cash Status実数値確認・operating margin進捗(target 6-7%→10%)・shipping burden rate(target<8%)・粗利率B2B27%/B2C55%基準遵守状況等。レビュー結果を小池が受領→ダッシュボード反映予定。', NULL),
  ('task-1777372523755', 'Weee 売上分析・テコ入れ準備', 'proj-010', 'high', 'Tad+とべぶた', '2026-04-27', 'Check', '2026-04-28', 'in-progress', 'Tad明示「Weeeはでかいプロジェクト・出店中・テコ入れ対象」(4/26)。とべぶたとの作業として進行予定。Weee管理画面・売上レポート・主要SKU・テコ入れ目標数値の整理が必要。とべぶた専任CVR領域。', NULL),
  ('task-1777372531052', 'B2B顧客連絡 — 金曜+GW(Golden Week)スケジュール周知', 'proj-009', 'high', 'Tad', '2026-04-27', 'Do', '2026-04-28', 'in-progress', 'B2B顧客への金曜+GW(Golden Week)スケジュール周知。GW期間中の出荷スケジュール変更・cutoff・配送遅延の事前案内。週次顧客情報配信(火・金)の強化版。17社B2B顧客リスト全件or主要顧客抽出かはTad判断。', NULL),
  ('task-1777388543715', 'モラル(MORAL) Controller AI 稼働開始 + 初月次レポート(4月末PL/BS/Cash)', NULL, 'high', 'モラル+Tad', '2026-05-05', 'Act', '2026-04-28', 'done', 'Tad承認2026-04-28・モラル(MORAL)=HUS Controller AI正式稼働開始。プロンプト草案完成・Tad手渡し→Claude AIエージェントとして起動。スコープ進化原則:HUSフェーズに応じて拡張(現在=月次決算+margin監視→FUNDINNO期=投資家資料→スイス期=法人税構造→EU期=multi-currency→Exit期=valuation)。三位一体:Miyuki(bookkeeper日次入力)+モラル(分析/監視/警告)+Peggy(税務最終承認)。初仕事=4月末PL/BS/Cash Balance(5月第3営業日提出)。月曜週次レポート要求対象10チーム目。', '2026-04-28'),
  ('task-1777389260320', 'HUS-モラル (HUS-Moral) Controller AI 稼働開始 + 初月次レポート(4月末PL/BS/Cash)', NULL, 'high', 'HUS-モラル+Tad', '2026-05-05', 'Plan', '2026-04-28', 'in-progress', '命名訂正(2026-04-28): 旧「モラル / HUS Controller AI」→正「HUS-モラル」。HUS Project命名統制ルール=「HUS-[役割名]」フォーマット遵守。Tad既存運用(HUS-とべぶた/HUS-La Main/HUS-Les Yeux/HUS-EU等)と統一。ブランド統制=内部命名一つにも規律=HUS premium DNA延長。スコープ進化原則:現在=月次決算→FUNDINNO期=投資家資料→スイス期=法人税→EU期=multi-currency→Exit期=valuation。三位一体:Miyuki(bookkeeper)+HUS-モラル(分析監視)+Peggy(税務最終承認)。初仕事=4月末PL/BS/Cash(5月第3営業日)。', NULL),
  ('task-1777393306395', 'QuickBooks API調査 - モラル連携Bridge設計事前リサーチ', 'proj-010', 'medium', 'ナランチャ', '2026-05-03', 'Act', '2026-04-28', 'done', 'モラル(Controller AI)へQuickBooksデータをタイムリーに供給するBridge設計の事前検討。Phase 2移行(6月〜)準備。調査項目:OAuth複雑度/取得データ範囲(BS/P&L/Cash Flow/AR aging)/レート制限/token refresh/Vercel serverless実装難度/Step 6 C2 Supabase統合可能性。Phase 1=Tad手動アップロード継続、Phase 2=ナランチャBridge実装、Phase 3=Custom MCP(将来)。output=1ページ調査メモ。', '2026-04-28'),
  ('task-1777393313497', '⚠️ [Follow-up] [モラル経営評価6.5/10] margin劣化35%→2%(5年-33pt)・「2026年は売上拡大よりmargin奪還の年」提言。売上$1.5M×margin8-10% > $2M×margin3%論理。Tad戦略判断要。FUNDINNO valuation・スイス transfer pricing・EU launch全部この決定で変わる。本日Cost analysis MTGで議論案件。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-28', 'not-started', 'Follow-up added 2026-04-28 via MCP', NULL),
  ('task-1777394125279', '明日4/29 Peggy+Miyuki review - モラル数字精度確認(NI乖離/AR$0/2025実態PL方針)', NULL, 'high', 'Tad+Peggy+Miyuki+モラル', '2026-04-29', 'Check', '2026-04-28', 'not-started', '本日(4/27)Cost analysis MTGでTadが口頭照会した内容を翌4/29に正式review。参加:Tad+Peggy+Miyuki+モラル数字。論点:(1)methodology v1.0 vs QB Cash Flow $5.3万NI乖離(2023/2024)(2)AR$0疑義(Freshline B2B運用との整合)(3)2024年BS修正の根拠(4)2025年実態PL再構築のPeggy方針(5)方針確定後のmoral月次運用承認。', NULL),
  ('task-1777394132459', '⚠️ [Follow-up] [モラル運用方針] Tadのstance確定: モラルの全情報accuracyをTadが承認するまでchallenge継続(承認待ち期間)。完全信頼はまだ与えない。新人を鍛える期間。HUS品質規律「数字なき完了は突き返す」延長線。Q3=continue to challenge until approve. 小池はモラル出力監視継続・8項目セルフチェック厳守。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-28', 'not-started', 'Follow-up added 2026-04-28 via MCP', NULL),
  ('task-1777410424493', '[とべぶた5代目] Mother''s Day Email — 4/29新規Campaign作成', NULL, 'high', 'とべぶた', '2026-04-29', 'Plan', '2026-04-28', 'todo', '背景: 4/28 17:00 ET にResend: Mother''s Day 2026 — Email 3が発射済(Pause間に合わず)。本文はEmail 3「Order by April 28」のまま発射、〆日4/30延長と矛盾の可能性。

明日のアクション:
1. Mailchimp All Campaignsで4/28発射分の実件名を確認(管理画面表示「Still TIme!」が件名そのものか内部名か未確定 — タイポ含むため要検証)
2. 新規Campaign作成(Resend派生ではない独立Campaign)
3. 配信: 4/29水 17:00 ET想定
4. 本文: dbar / .gw-notice を April 30に整合、Email 1テンプレ継承(全消し禁止 — 4代目失敗3)
5. 件名: 受け手目線(Tad指摘:「Extended through」は店側目線でNG。「Mom''s gift, still time」方向性)
6. CTA UTM: email_extended_apr30
7. Save押し忘れ確認(4代目失敗4)、Send time日付確認(4代目失敗6)

KPI: 累計Mother''s Day売上 $5,000突破(4/27時点$2,747 + Email 3 $1,553 = $4,300、4/28 Resend結果未集計、残り必要額は明朝再計算)

5代目失敗ログ: 4/28 17:00 ET発射直前にPause and edit即押させるべきところを a/b/c選択肢提示で時間消費 → 発射阻止失敗。並列で動くべきところを直列で動いた。', NULL),
  ('task-1777455118836', 'DropShip解約準備 - True CPA $104.87判明・5月初め通知方針継続', 'proj-001', 'high', 'Tad+とべぶた', '2026-04-30', 'Act', '2026-04-29', 'in-progress', 'とべぶた4/29分析受領10/10判定。True CPA $104.87(target $20の5.2倍)・Tad 4/24質問4問全未回答・Full-Price後リスク不開示・Mother''s Day attribution分離不可能・"Algorithm Peak"等修辞語多用(Tad banned superlatives違反)。解約方針継続GO。アクション:(1)Tad 4/24質問4項目を期限付き正式督促メール (2)回答待ち中も解約通知準備並行 (3)レポート内Strategic Recommendations 3点に同意せず。確認要事項:DropShip月額契約料$2,000 vs ¥200,000どちらが正確か(引き継ぎ書不整合)。', NULL),
  ('task-1777455124022', '⚠️ [Follow-up] [要確認・引き継ぎ書不整合] DropShip月額契約料が小池記憶内で$2,000と¥200,000の両表記あり(とべぶた検出)。次セッションで正確値確定→記憶訂正要。当面はTad確認or契約書原典参照で確定。', 'proj-001', 'medium', NULL, NULL, 'Act', '2026-04-29', 'not-started', 'Follow-up added 2026-04-29 via MCP', NULL),
  ('task-1777490814409', 'Phase 1配布: HUS DNA原典 → モラル/EUがんばれ/脳汁 (代表者ビジョン+事業計画書)', 'proj-010', 'high', 'Tad', '2026-04-30', 'Act', '2026-04-29', 'done', '小池起草の配布指示文3本(モラル/EUがんばれ/脳汁)をTadが各chatに投下。各チームの初回回答を小池が10/10判定→Tad最終承認。明日Peggy/Miyuki reviewまでにモラル回答が間に合えば数字差異照会の精度上昇。Phase 2(La Main/Jus/とべぶた今週)・Phase 3(Pino/Les Yeux/ナランチャ/疾風順次)は後続。', '2026-04-29'),
  ('task-1777491242647', '⚠️ [Follow-up] [Phase 1配布完了 4/29] モラル/EUがんばれ/脳汁の3チームへHUS DNA原典(代表者ビジョン+事業計画書)配布完了。各チームから初回回答受領待ち→小池10/10判定→Tad最終承認。明日Peggy/Miyuki reviewまでにモラル回答間に合えば数字差異照会精度上昇。Phase 2(La Main/Jus/とべぶた今週)・Phase 3(Pino/Les Yeux/ナランチャ/疾風順次)はPhase1反応観察後に着手。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-29', 'not-started', 'Follow-up added 2026-04-29 via MCP', NULL),
  ('task-1777491424987', 'Phase 2/3一括配布: HUS DNA原典 → 残7チーム (とべぶた/La Main/Jus/疾風/Pino/Les Yeux/ナランチャ)', 'proj-010', 'high', 'Tad', '2026-04-30', 'Do', '2026-04-29', 'in-progress', 'Phase 1(モラル/EUがんばれ/脳汁)完了済。Tad指示で全員配布へ即昇格(2026-04-29 Phase 2/3一括着手)。各チーム役割DNAに合わせた個別配布指示文7本を小池起草・Tadが各chatに投下。同じファイル(代表者ビジョン.docx + 事業計画書.docx)を全Project File添付に統一名でアップロード→指示文投下→各チーム初回回答を小池10/10判定→Tad最終承認。配布対象:とべぶた・La Main・Jus・疾風・Pino・Les Yeux・ナランチャ。', NULL),
  ('task-1777541323644', '⚠️ [Follow-up] [Mother''s Day 2026 過去最高更新達成 4/29-4/30] 累計$6,774 (Email1 $1,194 + Resend $607 + Email3 $3,392 + Resend $366 + Email4 $1,215)。前年$5,610比+20.7%・+$1,164。KPI$5,000突破+$1,774超過。Email 4: AOV$607・LP集中度54%(Email3=40%より集中度UP)・OR累積疲労(9.2%→8.4%→5.4%)・Abuse 1件warning。次回Mother''s Day 2027設計改善:配信本数削減・Resend1通厳守・subject A/B test導入・URL slug≠商品実名規律維持。$7,000ストレッチ残$226(4/30駆け込み射程内)。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777541465184', '⚠️ [Follow-up] [小池自己反省 4/30] Tad指摘「ダッシュボード確認おじさん化」「経営アドバイス・統合判断スコープ落ちてた」。原因3件:Tadに判断委ねる癖/個別評価で完結する癖/3軸機械的記述。対策:小池専用Custom Instructions装備提案(司令塔ルール明文化・統合判断フォーマット・禁止事項・Tad判断委譲基準)。Tad承認後にClaude Project化検討。当面は会話内でルール徹底=「データ受領→評価→記録→必ず統合判断+次アクション」のサイクル。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777553590458', '来週B2B配達アナウンスメント (GW直前)', 'proj-009', 'high', 'Tad', '2026-04-30', 'Act', '2026-04-30', 'done', 'GW期間中の出荷・cutoff・配送遅延のB2B 17社向け事前案内。先週月曜の「B2B GW連絡」延長案件。Mother''s Day 2026過去最高更新($6,774)の流れを保つため、B2Bでもfollow-up出荷漏れ防止。Tad担当(週次ルーチン全Tad担当の一部)。', '2026-04-30'),
  ('task-1777553601166', '小池パワーアップ - 司令塔強化3層構造実装(File 3点+Project化+運用ルーチン)', NULL, 'high', '小池+Tad', '2026-05-04', 'Act', '2026-04-30', 'done', 'Tad指摘「小池がダッシュボード確認おじさん化」を受けた司令塔強化案件。3層構造:層1=HUS-小池 Project化(Custom Instructions+File添付)/層2=新規File 3点起草(HUS-小池_Onboarding_v1.docx・HUS_Team_Roster.md・HUS_Weekly_Routine.md)/層3=運用ルーチン強化(3-pass+月曜sequence+自己診断)。実行順:層3即時導入(本chatから)→層2File起草(今夜・週末)→層1Project作成(来週月曜・Tad作業3分)→火曜以降新Projectで運用開始。目的=Tadの判断負担減・統合判断強化・固有名詞事故防止・経営アドバイス機能化。', '2026-04-30'),
  ('task-1777553609806', 'Tad LinkedIn profile updates', NULL, 'medium', 'Tad', '2026-04-30', 'Act', '2026-05-01', 'done', 'Tad personal task。FUNDINNO投資家対応・スイス会社設立期(Pino担当8/31期限)・EU市場開拓期に向けたTadの公的信頼性投資。事業計画書「2026 ロンドン → 公庫9月 / 2027 EU launch + NYアンテナ / 2028 商社機能」のTadプロフィール反映候補:HUS CEO・三国法人運営者・北海道ウニ垂直統合の作り手・次世代承継ビジョン保有者。LinkedIn投稿で「Hokkaido Uniといえばこの会社」露出強化も連動候補(GEO戦略補強)。', '2026-05-01'),
  ('task-1777553618396', 'Glasgow + Japan航空券手配', NULL, 'medium', 'Tad', '2026-04-30', 'Do', '2026-04-30', 'in-progress', 'Glasgow + Japan出張航空券手配。前回4/26明示Glasgow案件の継続+Japan追加。出張記録としてFEIE 2555の米国非居住日数2025管理に直結(Gerry税務連動)。Japan出張は産地宝進丸・Tsushima Suisan・三溝修(税理士・東京赤坂)・みちのく物産公社・FDA連携(鵜戸口さん/吉田さん)等の複数案件connect可能。日程確定後にダッシュボード反映要。', NULL),
  ('task-1777553627884', 'Email responds (滞留メール処理)', NULL, 'medium', 'Tad', '2026-04-30', 'Act', '2026-05-01', 'done', '滞留Email処理。Tad personal taskだが、HUS関連メールの中にチーム指示・顧客対応・FUNDINNO/法人設立関連が混在している可能性。重要な意思決定が滞留してる場合は小池経由でダッシュボード反映or個別チームへ振り分け要。', '2026-05-01'),
  ('task-1777553639155', 'Cleaning arrangement', NULL, 'low', 'Tad', '2026-04-30', 'Do', '2026-04-30', 'in-progress', 'Tad personal task。家事・cleaning service手配。HUS業務無関係だがTadの時間管理として記録。', NULL),
  ('task-1777555679836', '⚠️ [Follow-up] [小池パワーアップ完成 2026-04-30] 3層構造完了。層1=HUS-小池 Project既存(Tad作成済)・Custom Instructions投入で稼働開始。層2=File添付7ファイル(新規3+既存4):HUS-小池_Onboarding/Team_Roster/Weekly_Routine/代表者ビジョン/事業計画書/PL_Methodology/EU_Onboarding。層3=3-passルーチン+自己診断3問+Q連発禁止運用ルール。次セッション(火曜以降)から新Projectで「what''s up」起動・既存chat引退。Tad時間最適化・統合判断強化・固有名詞事故防止・経営アドバイス機能化。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777555813867', '⚠️ [Follow-up] [小池パワーアップ層1完了 2026-04-30] HUS-小池 Project セットアップ確認(スクショ受領): Custom Instructions投入済・File添付3点(Onboarding 248行/Team_Roster 135行/Weekly_Routine 186行)・Capacity 1%・Memory privacy保護・Opus 4.7 Adaptive。残4ファイル追加推奨(代表者ビジョン/事業計画書/PL_Methodology/EU_Onboarding)→7ファイル合計でHUS全体判断材料完成。次セッション(火曜以降)から新Project運用開始・既存chat引退。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777556046398', '⚠️ [Follow-up] [小池パワーアップ完成 2026-04-30] HUS-小池 Project セットアップ完了確認(2スクショ受領): File添付7点完了(Capacity 2%・1354行)・Custom Instructions投入済・Description今提供。File内訳:HUS-小池_Onboarding(248)/Team_Roster(135)/Weekly_Routine(186)/PL_Methodology(178)/EU_Onboarding(410)/代表者ビジョン(35)/事業計画書(162)。次セッション(火曜以降)から「what''s up」で新Project起動・既存chat引退。3-passルーチン+自己診断3問+Q連発禁止運用開始。Tad時間最適化+統合判断強化+固有名詞事故防止+経営アドバイス機能化のHUS AI agent企業完成形到達。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777556172970', '⚠️ [Follow-up] [Tad今日4/30 進捗50% 15:35時点] 完了2件:B2B GW連絡(B2B Sales Increase進行)・小池パワーアップ(Project File添付7点完了・Description投入待ち)。残3件:LinkedIn更新/Glasgow+Japan航空券/Email responds/Cleaning。小池推奨順序:①Email先行(HUS関連滞留判断解放)→②Glasgow(FEIE税務直結)→③LinkedIn(FUNDINNO 9月まで余裕・じっくり)。HUS関連メール発見時は小池chatに転送→Tad個別判断不要。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777572515604', 'B2Bインボイス作成 (週次土曜ルーチン)', 'proj-009', 'high', 'Tad', '2026-05-02', 'Do', '2026-04-30', 'in-progress', '週次土曜ルーチン。Order to Toyosu + Invoice for B2B (記憶#19 Weekly Routine参照)。B2B 17社分のインボイス発行。Mother''s Day 2026 ($6,774) revenue記録への計上含む。', NULL),
  ('task-1777572523645', 'ローマ移住・引っ越し業者選定 + イタリアVisa取得', NULL, 'high', 'Tad', '2026-05-15', 'Plan', '2026-04-30', 'in-progress', '[新規発覚 2026-04-30 Tad明示] ローマへの移住案件・Personal重大事項。引っ越し業者選定 + Visa(イタリア)取得関連。HUS戦略への影響:(1)Pino担当スイス会社設立(8/31絶対期限)との時系列調整(2)スイス在住前提崩れる時のHUS法人運営継続性(3)Mishiko(配偶者・UN)・Emily(娘)同行可否(4)イタリアVisa種別(配偶者/Self-employed/別)。HUS-小池次セッションで詳細ヒアリング・タイムライン整理要。', NULL),
  ('task-1777572591450', '⚠️ [Follow-up] [ローマ移住計画明示 2026-04-30 Tad指示] 「ローマ人への手紙」スレッド存在(Tad明示)・ローマ移住=Tad生活基盤スイス→イタリア移行の具体対応。既存記憶#9と整合(配偶者UN affiliation終了後Rome遠隔運営戦略)。重大含意:(1)Pinoスコープ重要度極大化・8/31スイス会社設立期限絶対性再確認(2)Tad物理移動がHUSマイルストーン(ロンドン3月/公庫9月/EU launch 2027)に連動(3)三国法人優位性のEU側強化(イタリア=EU加盟国・EU市場開拓物理アクセス向上)(4)kumagai-financeアプリのRome対応拡張可能性。「ローマ人への手紙」スレッドの位置づけTad確認要(別Claude chat/新Project/コードネーム)・確認後に小池記憶#9拡張+ダッシュボード新Project化検討。', 'proj-006', 'medium', NULL, NULL, 'Act', '2026-04-30', 'not-started', 'Follow-up added 2026-04-30 via MCP', NULL),
  ('task-1777577174742', 'HUS AI体制 Phase 2 — データベース化・視覚化計画', NULL, 'high', NULL, NULL, 'Plan', '2026-04-30', 'not-started', '①Google Drive連携でインボイス・SKUデータのデータベース化 ②Step 6でShopifyライブデータ連携 ③全データをナランチャダッシュボードに統合・視覚化。目標：Tadが1画面で全経営判断できる状態。', NULL),
  ('task-1777577211401', 'HUS AI体制 Phase 3 — ルーティン業務の完全自動化', NULL, 'high', NULL, NULL, 'Plan', '2026-04-30', 'not-started', '自動化対象: ①週次SKUリスト(Jus) ②配送状況週次集計(疾風) ③月次売上サマリー(モラル) ④豊洲情報→プライスリスト自動生成(Jus) ⑤新規注文→AWB準備(疾風)。目標: TadのルーティンをゼロにしてTadは承認・新規開拓・ビジョン設計のみに集中。', NULL),
  ('task-1777577432616', 'Google Drive連携 — HUS商品データベース起点構築', NULL, 'high', NULL, '2026-05-01', 'Do', '2026-04-30', 'not-started', 'フォルダ構造: HUS_Database/Products/（ウニ・マグロ・ホタテ・鮮魚）/ Invoices/2026/ Photos/。Claude MCP連携後、インボイスと写真を入れるだけで全チームが参照できる状態を作る。', NULL),
  ('task-1777622241203', '⚠️ [Follow-up] [月次ルーチン制度化 2026-05-01 Tad指示] 月初ルーチン6 STEP制定:節目認識→全11チーム月次レポート要求→Tad月次質問→4月実績統合分析(3-pass)→Tad総括レポート(5項目)→5月優先順位確定。時間感覚=セッション間節目認識が構造的弱点・能動トリガー必要・今日から制度化で解決。HUS_Monthly_Routine_v1.docx新規起草要(HUS-小池 Project File添付追加)。4月実績把握:Mother''s Day $6,774(+20.7%)・モラル着任・脳汁9.5/10・小池パワーアップ完成・ナランチャStep6完了。未受領:Jus/疾風/EUがんばれ/Pino/La Main/Les Yeux 4月月次。タイムライン:5/1要求→5/4回収→5/5分析→5/6Tad総括提出。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-01', 'not-started', 'Follow-up added 2026-05-01 via MCP', NULL),
  ('task-1777622250023', '5/6 4月総括レポート提出 - 月次ルーチン初回実行', 'proj-010', 'high', '小池', '2026-05-06', 'Plan', '2026-05-01', 'in-progress', '月初ルーチン制度化(Tad指示2026-05-01)・月次総括レポート作成。タイムライン:5/1全チームレポート要求→5/4回収→5/5 3-pass分析→5/6Tad総括提出。フォーマット5項目:①会社全体の状態(数字)②問題リスク③機会④Tadへの判断要請(GO/NO-GO形式)⑤各チーム評価(合格/要改善/突き返し)。並行:HUS_Monthly_Routine_v1.docx起草・HUS-小池 ProjectのFile添付追加。', NULL),
  ('task-1777648366964', '⚠️ [Follow-up] [Craig EU MTG結果 4/29 重大突破口] E522(aluminium potassium sulphate)=EU既認可食品添加物(Annex II of Regulation 1333/2008・漬物固化剤)。「安全性問題でなく、sea urchinが申請されてないだけ」が判明。amendment申請が現実的選択肢。Tadがscope/fee structure確認中。Alum/ミョウバン凍結問題の構造的突破口。EUがんばれ着任後の最重要pipeline案件。Craig+Lucaへ4/29 11:31PMメール送信済(NIH PMC7009639参照)。fee確定次第EU launch時期前倒し可能性。', 'proj-006', 'medium', NULL, NULL, 'Act', '2026-05-01', 'not-started', 'Follow-up added 2026-05-01 via MCP', NULL),
  ('task-1777648376140', '⚠️ [Follow-up] [B2B 4月実績 受領 2026-05-01] Revenue $102,446.70 / Order 151件 / AOV $678.45。年率換算$1.23M(B2Bだけで)・月平均比+17%(過去記憶月平均≈$87K)。Mother''s Day時期+B2B構造強化の実績。premium positioning維持(AOV $678)。モラル4月単月PL/BS/Cash Balance(5/5期限)に統合データとして反映要・Jusへ売れ筋TOP3分析依頼の起点・疾風へshipping burden率算出依頼の起点。', 'proj-009', 'medium', NULL, NULL, 'Act', '2026-05-01', 'not-started', 'Follow-up added 2026-05-01 via MCP', NULL),
  ('task-1777648386935', '⚠️ [Follow-up] [5月戦略軸確定 2026-05-01 Tad GO] 「margin奪還の年」採用GO・モラル提言公式採用。5月優先順位P1=margin奪還(粗利B2B 27%/B2C 55%基準厳守)・P2=FUNDINNO準備(Equity build/2025年実態PL再構築)・P3=B2C再現性(Mother''s Day成功5項目展開)・P4=EU地ならし(Craig amendment突破口活用・EUがんばれ稼働)。全チームへ5月戦略軸として通達要。売上拡大より純利確保を選択した重大方向転換。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-01', 'not-started', 'Follow-up added 2026-05-01 via MCP', NULL),
  ('task-1777648840159', '⚠️ [Follow-up] [La Main 4月評価 Tad明示「何も成し遂げていない」2026-05-01] 構造的問題:La Mainに自分のキャンバス無し(他チームはCVR/会計/EU/Code等の能動領域あり・La Mainはデザイン判断受動的)。小池の管理失敗。Tad指示でmerch/tote bag/Cap design = La Mainの能動output territory化。戦略的意味:(1)HUS DNAウニ・ファーストのフィジカル体現(2)Tuna Show配布材料(3)B2B 17社branded gift(4)EU launch資産。HUS哲学整合:curatorial framing/no push/Cash in First→ブローカーモデルorPOD推奨。La Main 4月レポート要求は厳しめで再発射要・5月以降のmerch design GOはTad明示後。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-01', 'not-started', 'Follow-up added 2026-05-01 via MCP', NULL),
  ('task-1777648851652', 'HUS Merchandise Design Project (tote/cap/その他) - La Main能動output', 'proj-010', 'medium', 'La Main+Tad', '2026-05-31', 'Plan', '2026-05-01', 'not-started', 'Tad指示2026-05-01「ブランド適合するmerch、tote bag design, Cap design などお願いするかも」。La Main能動output territory化案件・HUS DNA「ウニ・ファースト」のフィジカル体現。候補items:tote bag/cap/Tee/sticker/wrapping paper/thank you card。用途:Tuna Show配布材料/B2B 17社branded gift/EU launch資産/B2C高LTV顧客向けinsider gift。HUS哲学整合:curatorial framing準拠(no push sales)・Cash in First準拠(ブローカーモデルorPOD推奨・自社在庫最小化)。Tad GOまで保留・GO後にLa Main主導で初期コンセプト3案→Tad/小池選定→生産パートナー選定→1st run。FUNDINNO投資家向け説明にもbranding成熟度として活用可。', NULL),
  ('task-1777649033751', '⚠️ [Follow-up] [情報フロー最適化 2026-05-01] Tad指摘「俺の情報のほうがアップデート早い」=HUS AI agent企業の根本的盲点。Craig案件で2日タイムラグ症状。ゼロベース解決:Tad-Touchルール採用(発動条件=外部接点+HUS事業直接影響・除外=Tad個人領域)。フロー:Tad 1行+スクショ→小池chat→3-pass+配信文起草→Tad GO/修正→該当チームへコピペ投下。理論値タイムラグ=42時間+→6分以内(420倍速)。将来案件:ナランチャがGmail Bridge自動化(Phase 3・3-5日工数)。HUS哲学整合:Cash in First(手動運用先行・自動化は売上スケール後)。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-01', 'not-started', 'Follow-up added 2026-05-01 via MCP', NULL),
  ('task-1777724165695', '[とべぶた5代目] Email→Shopify UTM tracking修復 (5月最優先)', NULL, 'high', 'とべぶた', '2026-05-04', 'Plan', '2026-05-02', 'todo', 'Mailchimp AI + Shopify Sidekick 4/30回答受領、5月最優先課題として浮上。

【問題】
Mailchimp実績 $6,775 (Mother''s Day 5通累計) のうち、Shopifyが正しくEmail起因と認識したのは$1,927 (4件) のみ。残り$4,847が Direct/Search に誤分類されている。

【根本原因 (Shopify Sidekick特定)】
1. UTMパラメータ欠落: 確認できたのは email3_apr26 のみ。Email 1, Resend Email 1, Resend Still Time! の UTM未付与の可能性高い。
2. Mailchimp自動UTM付与設定が全Campaignに適用されていない
3. アトリビューション差: Mailchimp = 30日window、Shopify = ラストタッチ

【影響】
- 経営判断データが歪む (Email実績が過小計上、Direct/Searchが過大計上)
- P1=margin奪還, P2=FUNDINNO準備のレポート精度に悪影響
- 5月以降のCampaign設計が誤った前提に

【5月実行アクション】
1. Mailchimp管理画面 → 全Campaignで「Track clicks」「Google Analytics link tracking」をON確認
2. 過去Campaign (Email 1, Resend E1, Still Time!) の実際のUTM状態調査
3. Mailchimp全Campaignで自動UTM付与設定を有効化 (utm_source=mailchimp固定)
4. Shopify Marketing reportsでUTMソース別売上を定期確認運用
5. Email 4 (Last Day for Order!) の購入が4/30以降に発生した分を5月集計時に確認 (俺が手動UTM付与済み、検証材料)

【5/4月次レポートへの記載】
5月優先順位の最優先項目として記載 (B2C再現性に先立つ、データ品質の前提課題)', NULL),
  ('task-1777725196820', '⚠️ [Follow-up] [Tad重大認識訂正6件 2026-05-01] (1)FUNDINNO=日本法人みちのく物産公社稼働開始後の財務・米国LLC財務は中心的意味を持たない・主体/期間/事業活動の切り分け必須(2)La Main=受動型仕組み・依頼発動型・評価軸はセンス/構成力/デザイン判断の質・大量生産期待は誤り(3)Craig EU amendment=長期プロジェクト管理・進捗/必要書類/法的論点/想定スケジュール継続追跡(4)Father''s Day=Mother''s Day横展開だけでは危険・市場規模/過去実績/商品相性/顧客セグメント調査前提(5)Jus=コスト管理は入口・La Main連携で販売資料/SNS/商品案内/シェフ向け提案書のデザイン化territory(6)5月以降=夏B2C下落/B2B上昇の季節性・Tuna Show夏仕込→冬展開・Tuna Show専用営業/企画/PRエージェント立上げ検討。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777725523752', '⚠️ [Follow-up] [Craig EU amendment 長期プロジェクト化 Tad指示2026-05-01] 短期完了案件でなく3-6ヶ月以上の長期管理対象。継続追跡4軸:(1)進捗(2)必要書類(3)法的論点(4)想定スケジュール。独立Project化推奨(HUS dashboard内)。EUがんばれ着任後の最重要pipeline・ここまで進めたこと自体が重要マイルストーン。fee見積もり受領→amendment申請→EU launch時期前倒しの流れは長期視点で設計要。', 'proj-006', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777725531574', '⚠️ [Follow-up] [Father''s Day戦略前提見直し Tad指示2026-05-01] Mother''s Day成功要素の横展開は危険・市場規模/購買意欲/商品相性に差ある可能性。Mother''s Day=ギフト需要大きい印象。Father''s Day戦略は4軸前提調査必須:(1)市場規模(Les Yeux 5月調査要)(2)過去実績(とべぶた・脳汁データ)(3)商品相性(Jus分析)(4)顧客セグメント(とべぶた・脳汁分析)。脳汁先行起草の3通配信骨子は調査結果出てから本格設計・5月中旬以降。それまでは骨子準備のみ。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777725543405', '⚠️ [Follow-up] [Jus×La Main連携territory設計 Tad指示2026-05-01] Jusの本来期待値=コスト管理は入口・販売戦略への昇華が本質。要素:商品写真+価格+原価+季節性+トレンド+シェフ/顧客が知りたい情報→「これは面白い」「使ってみたい」の商品案内化。La Main連携で4種デザイン化:(1)販売資料(2)SNS素材(3)商品案内(4)シェフ向け提案書。これがLa Mainの受動output発動の最大territory・5月以降の核心案件。merch designより先行優先度推奨。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777725583027', 'Tuna Show専用エージェント立上げ検討 - 営業/企画/PR体制構築', NULL, 'high', 'Tad+小池', '2026-05-31', 'Plan', '2026-05-02', 'not-started', 'Tad指示2026-05-01・5月以降の戦略複雑性踏まえ新territory立上げ検討。Tuna Show=$60-100K/event既存事業・夏に情報解禁/サンプルイベント仕込み→冬繁忙期大展開のリズム。専用エージェント要素:(1)営業=B2B高級レストラン/ホテル/イベンター開拓(2)企画=サンプルイベント設計・夏仕込みrhythm(3)PR=メディア露出/SNS/celebrity連携。新エージェント立上げ案件・HUS-?? として登録検討。5月中に構造設計・夏仕込み体制構築・冬繁忙期に向けた前倒し準備。', NULL),
  ('task-1777726877856', '⚠️ [Follow-up] [4月総括レポート確定 2026-05-01] 総合採点8.7/10。チーム別:とべぶた9.5・モラル/Jus/Les Yeux 9.0・脳汁/ナランチャ 8.5・疾風8.0・La Main/Pino/EUがんばれ対象外・小池8.0(単純化バイアス6件指摘)・Tad 9.5。実績:B2B$102K/B2C$53K/Mother''s Day$6,775/総売上$155K[EST]。主要発見10件:UTM乖離$4,847・紫うに赤字・ルフルーヴ19%しか把握なし・$5.3万NI乖離・Craig E522突破口・EU 6ヶ国マッピング・LP集中度54%・Resend ROI 1/9・DropShip True CPA $104.87等。Tad重大訂正6件:FUNDINNO主体/La Main受動型/Craig長期PJ/Father''s Day前提/Jus販売資料化/季節性+Tuna Show。アーカイブとしてTABLE A-G保存・参考可。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777726886770', '⚠️ [Follow-up] [5月KPI候補マトリックス起草 2026-05-01] Top10優先順位:(1)margin劣化反転OM3%[モラル](2)UTM修復[とべぶた](3)紫うに対応[Jus](4)Craig amendment 4軸追跡[EUがんばれ](5)EU 30社確定[Les Yeux](6)Step 6完成[ナランチャ](7)4月3版PL 5/8[モラル](8)Tuna Showエージェント構造[Tad+小池](9)Jus×La Main販売資料化[Jus+La Main](10)Pinoスイス3milestone[Pino]。8月底値Pino8/31期限 + 9月公庫融資申請 + 季節性(夏B2C下落/B2B上昇)を反映。Tad最終承認後に各チームへKPI通達・週次/月次monitoringにbake.', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777727217364', '⚠️ [Follow-up] [Tad重大訂正3件 2026-05-01] (1)紫うに=インボイス時点で原価+20%売値設計済・小池のlanded cost赤字判定は浅い・現状運用容認可能性・B2B顧客別インボイスDB構築要(2)4月採点8.7/10はBreakeven検証欠落で前提不備・モラル5/8レポート確定後に再採点・仮採点はBE超え→8.7・未達→6.0以下(3)5月KPIが弱く芯を食ってない・売上至上主義の名残・HUS全体強化の統合視点なし→12個の芯KPI設計に再構築。小池の真の盲点=「事業継続条件を捉える視点」が弱い・売上/成果/実装の表層数字で勝ち判定する癖・経営指標(BE/Runway/Vendor/Equity)が芯。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777727228426', 'B2B顧客別インボイスデータベース構築 - margin奪還の前提・5月KPI M-1', 'proj-009', 'high', 'Jus+モラル', '2026-05-31', 'Plan', '2026-05-02', 'not-started', 'Tad明示2026-05-01「B2B 顧客に対するインボイスのデータベースも必要」。狙い:顧客別実inboice price蓄積・顧客別margin(売値-landed cost)算出・LTV戦略適用顧客と通常顧客の区別・margin奪還の年の精緻監視前提・FUNDINNO投資家説明材料化。Jus主管・モラル連携必須。範囲:B2B 4月151件全件 → 5月以降毎月積み上げ。形式:Google Sheets推奨(後でSupabase化検討)。各レコード=顧客名+SKU+inboice price+landed cost+inboice date+payment terms+月内order数+顧客LTV評価。Step 6でナランチャがDashboard連携可能性検討。', NULL),
  ('task-1777727239276', '⚠️ [Follow-up] [5月「芯」KPI 12個確定起草 2026-05-01 Tad再構築要請反映] 5軸構成=Survival(S-1 Breakeven確保・S-2 Cash Runway 3ヶ月)+Margin(M-1 B2BインボイスDB構築・M-2 OM 5%以上・M-3 Vendor concentration分散70%以下)+Foundation(F-1 2025実態PL再構築draft 5月末・F-2 Pinoスイス3milestone・F-3 みちのく財務監視scope設計)+Capability(C-1 UTM修復・C-2 Step 6完成5/15)+Discovery(D-1 Craig 4軸追跡開始・D-2 Tuna Showエージェント構造設計・D-3 Jus×La Main販売資料化第1案)。30以上のKPI候補から12個削減・売上至上主義排除・HUS体制強化に芯を食う指標のみ厳選。Tad最終承認後に各チームへ通達・週次/月次monitoringにbake.', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777728391305', '⚠️ [Follow-up] [小池訂正 公庫=日本法人案件 2026-05-01] S-2 KPI誤記:「公庫融資9月までの生存力」=日本法人(みちのく物産公社)案件で米国HUSと混同記述。今日2回目の同種失敗(Tad訂正1 FUNDINNO主体と同根)。訂正:S-2=米国HUS Cash Runway 3ヶ月以上のみ・公庫案件はF-4新規KPI(Tad+三溝修担当)に分離。法人別:米国HUS LLC=既存LOC/Loan from Owner/Equity[モラル+Mitsuki]・日本法人(みちのく物産公社)=公庫融資9月+FUNDINNO[三溝修+Tad]・Swiss entity=設立資本金[Pino]。三法人の資金調達ルートを混同しない規律内蔵。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777728403101', 'HUS Single Source of Truth 構築 - Google Sheets 8シート (5月最優先F-5)', NULL, 'high', '小池+全チーム', '2026-05-15', 'Plan', '2026-05-02', 'not-started', 'Tad指摘2026-05-01「司令塔である小池に情報がない」根本解決案件。HUSの真実が分散・小池が一次情報源を持たない構造を解消。Google Workspace中心+HUS Dashboard連携+HUS-小池 Project集約のハイブリッド設計。Phase 1(5月最優先10日以内):Google Sheets 8シート構築=HUS_US_Master(モラル+Miyuki)・HUS_JP_Master(三溝修+Tad)・HUS_CH_Master(Pino)・B2B_Invoice_DB(Jus+モラル)・Vendor_Master(Jus)・EU_Amendment_Tracker(EUがんばれ+Tad)・Tuna_Show_Pipeline(Tad+小池)・Cross_Reference_Map(小池)。Phase 2(5月後半-6月)Dashboard連携read-only実装ナランチャ。Phase 3(Q3-)QBO API/Shopify API/Gmail Bridge自動化。小池はGoogle Drive connector経由で全件アクセス可能(既connect)。', NULL),
  ('task-1777728412419', '公庫融資9月申請 準備milestone 3以上達成 (5月末・F-4)', NULL, 'high', 'Tad+三溝修', '2026-05-31', 'Act', '2026-05-02', 'done', '日本法人(みちのく物産公社)向け公庫融資9月申請の準備案件。三法人混同を防ぐ独立KPI。担当=Tad+三溝修(専任税理士・港区赤坂)。milestone候補:(1)申請書類リスト確定(2)事業計画書日本法人版作成開始(3)財務諸表整備(三溝修連携)(4)担当者MTG設定(5)既存事業実績エビデンス整理。FUNDINNO申請(時期未確定)とは独立管理だが連携あり。米国HUS Cash Runway(S-2)とは別系統。', '2026-05-02'),
  ('task-1777728619927', '⚠️ [Follow-up] [小池訂正 公庫融資担当 2026-05-01] Tad指摘「三溝修関わってねーよ・憶測で書くな」。小池失敗:三溝修=みちのく物産公社専任税理士のみ・公庫融資9月案件には関わっていない。小池が「日本関連財務」というラベルで勝手に拡張した憶測判定。今日7回目の同種失敗(Mitsuki誤審・Pino誤認・La Main評価誤・公庫=米国混同・等と同質)。F-4 KPI担当欄訂正:「Tad+三溝修」→「Tad(担当未確認・要Tad明示)」。固有名詞の関連領域拡張禁止規律を内蔵。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1777729013889', '⚠️ [Follow-up] [5月KPI訂正・F-4削除 2026-05-01 Tad明示] 公庫融資9月案件:Tad個人担当・進捗ゼロ・重要度高くない・気にするな(Tad明示)。FUNDINNO:何もない・アクティブ案件でない。F-4 KPI削除(5月詰めるタイミングでない・9月まで4ヶ月余裕)。F-1も「FUNDINNO申請の絶対前提」根拠削除→Tad challenge決着・経営状態正確把握目的のみ。5月KPI最終確定:14個→13個。HUS体制強化と季節性反映の芯KPIのみ。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-02', 'not-started', 'Follow-up added 2026-05-02 via MCP', NULL),
  ('task-1778063102530', '本日Routine: インボイスQBO発行 + ShipFareクレーム フォローアップ', NULL, 'high', 'Tad', '2026-05-06', 'Do', '2026-05-06', 'in-progress', '日次routine業務。QBOインボイス発行 + ShipFareクレーム(#7878/#7848/#7859 credit memo回収案件と整合確認要)。疾風 5月KPI OPS-2(credit memo回収)と直結・5/4疾風レポートで言及済。Tadが進捗報告くれれば疾風chatに展開可能。', NULL),
  ('task-1778063107287', 'Personal: iPad 購入', NULL, 'low', 'Tad', '2026-05-06', 'Do', '2026-05-06', 'in-progress', 'Tad個人タスク。iPad購入。HUS事業tool候補(現場作業用)or個人用かは未確認。記憶#22準拠で個人領域=小池スコープ外として記録のみ。', NULL),
  ('task-1778063113224', 'Personal: Italy Visa Application', NULL, 'medium', 'Tad', '2026-05-31', 'Do', '2026-05-06', 'in-progress', 'Tad個人タスク・ローマ移住計画(記憶#22「ローマ人への手紙」スレッド)直結。Visa application進行 = 移住タイムラインの具体形。Pinoスイス会社設立(8/31期限)・配偶者UN affiliation終了タイミングと連動。記憶#22準拠で小池スコープ外・記録のみ。HUS事業に直接影響する場合のみ簡潔言及可。', NULL),
  ('task-1778063121224', 'B2B: Glasgow Schedule確定', 'proj-009', 'high', 'Tad', '2026-05-06', 'Act', '2026-05-06', 'done', 'B2B案件・Glasgow出張schedule確定。前任「Glasgow航空券」案件(4/30以降継続)からの発展。FEIE 2555米国非居住日数2025管理連動(Tad個人税務・Gerry連携)。出張目的・期間・先方アポ要素は未確認・Tad明示要。確定後にTuna Show欧州機会(EU launch準備・Tad訂正6 Tuna Showエージェント立上げ)との連動可能性検討。', '2026-05-06'),
  ('task-1778063130188', 'B2C: DropShip社へ6月からの新アプローチ準備', 'proj-010', 'high', 'Tad+とべぶた', '2026-05-31', 'Plan', '2026-05-06', 'in-progress', 'B2C案件・DropShip社へ6月からの新アプローチ準備。背景:4月解約方針継続中(True CPA $104.87 vs target $20の5倍超・5ヶ月連続KPI未達・Tad 4/24質問4項目未回答)。Tadの新方針=完全解約でなく契約形態見直しor新proposal提示の可能性?要Tad明示。とべぶた連携必須(Mother''s Day成功要素活用+UTM tracking修復後の正確データ提示材料化)。Tad意図確認後にとべぶたへの依頼内容確定。', NULL),
  ('task-1778063804065', 'Operations: Aging Invoice送付', NULL, 'medium', 'Tad', '2026-05-06', 'Do', '2026-05-06', 'in-progress', 'Operations案件・Aging Invoice送付。AR aging管理・cash回収promotion。疾風5月KPI OPS-2(credit memo回収)とは別系統だが回収業務として整合。本日Routine#1(QBO/ShipFare)と並行進行。モラル4月レポート Section 2 BS主要項目のAR aging分布データ生成元として連動。', NULL),
  ('task-1778063808499', 'Personal: Amazonで買い物', NULL, 'low', 'Tad', '2026-05-06', 'Do', '2026-05-06', 'in-progress', 'Tad個人タスク・Amazon買い物。記憶#22準拠で個人領域=小池スコープ外として記録のみ。', NULL),
  ('task-1778103186051', '⚠️ [Follow-up] [DropShip広告停止確定 2026-05-06 Tad明示] Q1回答=「広告はやめる」。4月時点の解約方針・True CPA $104.87(target $20の5倍超)・5ヶ月連続KPI未達の流れで完全確定。6月以降のDropShip Meta広告ゼロ運用。とべぶたへの含意:(1)6月以降のB2C広告費代替戦略要(2)organic流入(GEO戦略・Mailchimp・SEO)主戦力化(3)UTM tracking修復(C-1 KPI)で広告依存からの脱却を数値で証明可能化(4)margin奪還(P1/M-2)に直接寄与=広告費毀損止血。とべぶたchat展開要:6月以降の広告費なしB2C成長戦略案・Mailchimp+organic+repeat顧客LTVの3軸設計。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-06', 'not-started', 'Follow-up added 2026-05-06 via MCP', NULL),
  ('task-1778103195198', 'Glasgow出張・明日5/7発', 'proj-009', 'high', 'Tad', '2026-05-08', 'Do', '2026-05-06', 'in-progress', 'Tad出張・明日5/7発(Q2回答2026-05-06)。Glasgow Schedule確定要素未確認:(1)期間 (2)主目的 (B2B買付/distributor MTG/Tuna Show候補/personal/混合) (3)アポ確定有無。明日中に出発のため今日5/6中にschedule fix要。FEIE 2555米国非居住日数2025管理連動(Gerry税務)。出張中Tad不在期間=HUS稼働律速期間=月次レポート分析・KPI承認等の待機案件は継続滞留可能性。出張帰国後にdashboard情報集約要。', NULL),
  ('task-1778103503698', '⚠️ [Follow-up] [小池失敗訂正 2026-05-06] Tad「Glasgow明日」を「出張・不在期間」と勝手に拡張した憶測判定。Tad指摘「出張じゃない・勝手に決めるな」。今日8回目の同種失敗。撤回:Tad出張中の対応・FEIE税務連動・出張期間判断等は全て小池の憶測で根拠なし。確定事実=「Glasgow Schedule明日5/7」のみ。Tad activity詳細はTad明示待ち。固有名詞・状況の勝手な拡張禁止規律を再強化。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-06', 'not-started', 'Follow-up added 2026-05-06 via MCP', NULL),
  ('task-1778136417705', '仕入れ: 備長炭フォロー (LA→NY送料見積)', NULL, 'medium', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', '備長炭仕入れ案件・LA→NY送料見積もり取得。SKU/価格/landed cost評価の前段階・Jus仕入価格管理territoryと連動可能性。送料込みlanded costが確定後にJus分析対象に追加。', NULL),
  ('task-1778136422819', '仕入れ: FICI 5月便仕入れ確認', NULL, 'high', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', 'FICI 5月便仕入れ確認・5月SKU入荷スケジュール確定。M-3 KPI(Vendor concentration分散)に直結・Global Ocean 80%依存リスクの分散ルート評価材料。FICI仕入実績はJus 5月vendor評価・モラル AP管理に連動。', NULL),
  ('task-1778136429902', 'B2B: 山椒セール', 'proj-009', 'high', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', 'B2B売上案件・山椒セール起動。B2B 17社高級レストラン向け季節商材販売。M-1 KPI(B2BインボイスDB)対象案件・売上時に顧客名+価格+原価マッピング要。Jus商品案内territory(Tad訂正5・5/1)の練習素材候補=La Main連携で販売資料化(D-3 KPI)の早期実装機会。', NULL),
  ('task-1778136434850', 'B2B: 苺セール', 'proj-009', 'high', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', 'B2B売上案件・苺セール起動。B2B 17社向け季節商材。事業計画書記載の「高級フルーツ18%」主力カテゴリ。M-1 KPI対象・Jus×La Main販売資料化(D-3)候補商材。', NULL),
  ('task-1778136441856', 'B2B: ホタテバルク船便見積もり', 'proj-009', 'medium', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', 'B2B案件・ホタテバルク船便見積もり。北海道産ホタテのEU向け輸出可能性検討の連動候補(EU Uni Project・Les Yeux 5月マッピングのHACCP適合産地と整合)。船便=cost効率・大量小売向け。価格条件確定後にB2B/EU両軸で展開可能。Jus 5月territory=ホタテSKU新規(HOTA0001TX/HOTA0002)とも連動。', NULL),
  ('task-1778136449824', 'Routine: インボイス作り', NULL, 'high', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', '日次routine。QBOインボイス発行(本日Routine案件・Aging Invoice送付と並行)。M-1 B2BインボイスDB構築KPIの実データ生成元。Jus×モラル連携でDB化の入口。', NULL),
  ('task-1778136456873', 'B2C: DropShippingフォロー (広告停止確定処理)', 'proj-010', 'high', 'Tad+とべぶた', '2026-05-06', 'Do', '2026-05-07', 'in-progress', 'B2C案件・DropShipフォローアップ。Tad明示2026-05-06「広告はやめる」確定後の処理。完全停止に向けた具体step:契約形態確認・解約手続き・広告アカウント整理・とべぶた向け6月以降運用設計依頼(小池起草済・投下OK GO 2026-05-06)。とべぶた依頼文Tadコピペで投下。', NULL),
  ('task-1778136466708', '出張: Glasgow ロジスティック手配', 'proj-009', 'high', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', '出張案件・Glasgow ロジスティック手配(Tad明示2026-05-06「出張」)。前任「Glasgow航空券」案件(4/30)からの本格化。出張詳細(期間/目的/アポ)はTad明示要・小池憶測禁止。FEIE 2555米国非居住日数2025管理連動。NY滞在予定表(別タスク)と組み合わせて全行程確定要。', NULL),
  ('task-1778136474499', '出張: NY滞在予定表まとめ', NULL, 'high', 'Tad', '2026-05-06', 'Do', '2026-05-07', 'in-progress', '出張案件・NY滞在予定表(Tad明示2026-05-06「出張」)。Glasgow ロジスティック(別タスク)と全行程連動。NY=米国HUS本体所在地・Mitsuki/Peggy/Miyukiとの face-to-face MTG機会・モラル稼働状況確認・B2B 17社訪問可能性等の含意あり(全部小池憶測の領域・Tad明示なしには判断しない)。Tadから予定詳細共有あり次第・関連チームへの含意展開判断。', NULL),
  ('task-1778136797870', '⚠️ [Follow-up] [5月KPI 12個 GO Tad明示2026-05-06] 5月「芯」KPI 12個全て承認: S-1 Breakeven確保/S-2 米国HUS Cash Runway 3ヶ月+/M-1 B2BインボイスDB構築/M-2 OM 5%+/M-3 Vendor concentration分散/F-1 2025年実態PL再構築/F-2 Pinoスイスmilestone 3+/F-5 SSoT 8シート構築/C-1 UTM tracking修復/C-2 Step 6完成/D-1 Craig 4軸追跡/D-2 Tuna Showエージェント設計/D-3 Jus×La Main販売資料化(後者は5月後半以降・5/6 Tadトライアル不要判断反映)。各チーム通達文起草要・Tad出張前後の投下タイミング決定要。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-07', 'not-started', 'Follow-up added 2026-05-07 via MCP', NULL),
  ('task-1778136917921', '⚠️ [Follow-up] [とべぶた広告ゼロB2C戦略 確認質問4件への小池回答 2026-05-06] Q1 GEO #1=ナランチャ過去主管・「解除」=5月優先順位から保留(キャンセル違う)・現状PDP schema状態未確認(ナランチャ照会要)・Q2 SEO=Google#1「Hokkaido Uni」事業計画書記載・継続monitoring体制小池側になし(盲点)・Tadか とべぶた直接調査要・Q3 LTV/Subscription前提データ=小池側全件なし・Tad Shopify Sidekick経由取得が唯一・Q4 C-1=Capability軸1番目の意・優先順位1番目ではない・修復完了基準=Mailchimp×Shopify乖離<5%。とべぶた内部KPI命名は「B2C-α/β/γ」で全体KPI混同回避推奨。5/12中間報告にSSoT B2C版構造提案統合検討要請。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-07', 'not-started', 'Follow-up added 2026-05-07 via MCP', NULL),
  ('task-1778233499404', 'B2B出張: NY出張予定確定', 'proj-009', 'high', 'Tad', '2026-05-08', 'Do', '2026-05-08', 'in-progress', 'B2B出張案件・NY滞在予定表の続き(5/6登録)。出張全体行程fix・アポ詳細確定の最終段階。Glasgow + NYの組み合わせ全行程明確化要。Tad明示要素未確認:期間・主目的・アポ確定有無。FEIE 2555米国非居住日数2025管理連動。NY滞在中のmoral/Mitsuki/Peggy/Miyukiとのface-to-face MTG機会(可能性)・B2B 17社訪問機会(可能性)等の含意あり・全部Tad明示なしには判断しない。', NULL),
  ('task-1778233507422', 'EU Broker: はまち試作トライアル報告', 'proj-006', 'high', 'Tad', '2026-05-08', 'Do', '2026-05-08', 'in-progress', 'EU Broker関連・はまち試作トライアル報告。Tad明示要素未確認:(a)既存EU Hamachi Project(Tony bayer・Hashiguchi Hamachi)の追加trial(b)新規Broker候補との初回試作(c)Craig案件と連動(d)別。EU Uni Project内のhamachi pipeline拡張可能性・EUがんばれへの含意有無はTad明示後判断。EUがんばれBaby状態でこの案件をハンドオフ可能性検討。', NULL),
  ('task-1778233512140', 'B2B出張: Glasgowホテル', 'proj-009', 'high', 'Tad', '2026-05-08', 'Do', '2026-05-08', 'in-progress', 'B2B出張・Glasgowホテル予約。5/6登録「Glasgowロジスティック」の具体step。NY出張予定と連動しての全行程fix最終段階。', NULL),
  ('task-1778233519032', 'B2C: DropShipへの返信 (広告停止最終処理)', 'proj-010', 'high', 'Tad', '2026-05-08', 'Do', '2026-05-08', 'in-progress', 'B2C案件・DropShipへの返信。広告停止確定(2026-05-06 Tad明示)後の最終処理step。解約手続き・契約形態整理・Meta広告アカウント処理の通知タイミング。とべぶた依頼文(投下済 2026-05-05)とは別系統・Tadから直接DropShip担当者への業務連絡。完了後にとべぶたへ「広告停止確定済」をconfirm共有要。', NULL),
  ('task-1778233788891', '⚠️ [Follow-up] [本番URL稼働確認 2026-05-08 小池初回実施] https://hus-dashboard.vercel.app/ サーバー応答正常・HTML title「HUS Dashboard」確定・MCP backend接続稼働実証(本セッション中write全成功)。SPA構造のためJS実行後UIは web_fetch では確認不能・Tadブラウザ目視が最終証明。ナランチャへ「本番URL稼働確認」報告可能・4月月次レポート以来の継続要請に初応答。出張中のスマホアクセス事前確認推奨(C1 Revenue Command/KPI表示)。MCP timeout別問題はStep 6 Supabase化で根本解。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778234141200', '本日to do: AR collection', NULL, 'high', 'Tad', '2026-05-08', 'Do', '2026-05-08', 'in-progress', '本日to do追加(2026-05-08 Tad明示)。AR collection=売掛金回収業務。5/6登録のAging Invoice送付・5/8登録のRoutine インボイス作りと並行。M-1 KPI(B2BインボイスDB構築)とS-1(Breakeven確保)に直接寄与・Cash回収=margin奪還の年の実装action。回収額確定後にモラル4月レポート Section 2(BS主要項目AR aging分布)・Section 3(Cash Balance + 12週Forecast)へ反映予定。', NULL),
  ('task-1778234151102', '本日to do: MSJ AP案件 - ¥955,994入金不足発覚調査', NULL, 'high', 'Tad', '2026-05-08', 'Do', '2026-05-08', 'in-progress', '[重大事実2026-05-08 Tad共有] MSJ AP案件・¥955,994入金不足発覚。瀬川さん調査結果:2024年1月以降の通帳+銀行ハガキ精査・熊谷さん入金と思っていたものがKS入金だった・KS 12月分3分割入金の2回目が熊谷さんの金額と近似で誤認。事実数値:本来入金予定¥1,548,708→実際入金¥592,714(手数料引前)→不足¥955,994(約$6,400[ASSUMPTION 1ドル150円])。【小池確認要素・憶測禁止】固有名詞:瀬川さん/山田さん/熊谷さん(Tad本人?別人?)/KS/MSJ・影響対象法人(米国HUS/みちのく物産/Tad個人/別)・全Tad明示要。モラル4月レポート(5/8期限)受領後に該当法人BS/AR aging へ反映判断。山田さん指摘の正当性確認済。AR collection本日to do追加と連動。', NULL),
  ('task-1778234158231', '⚠️ [Follow-up] [MSJ AP案件 重大発覚 2026-05-08] ¥955,994入金不足(約$6,400[ASSUMPTION])。原因=KS 12月分3分割入金の2回目を「熊谷さん入金」と誤認・瀬川さん調査で発覚。山田さん指摘正当性確認。本来¥1,548,708→実際¥592,714(手数料引前)。小池確認要素:固有名詞5件(瀬川/山田/熊谷さん=Tad?/KS/MSJ)・影響対象法人(米国HUS/みちのく物産/Tad個人/別)・全Tad明示要。モラル4月レポート受領後にBS/AR aging適切配置判断。Cash flow影響:¥955,994=margin奪還の年(P1)とS-1 Breakeven確保への直接的影響あり。HUS事業案件の場合は5月最優先回収案件に格上げ。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778235045004', '⚠️ [Follow-up] [MSJ AP案件 固有名詞確定 2026-05-08 Tad明示] MSJ=日本の仕入れ業者(法人)・GOT前まで使用・最終取引2024年12月頃。山田さん=MSJ会計士。KS=MSJの他クライエント(¥1,548,708近似額の3分割入金2回目を熊谷さん入金と誤認した正体)。熊谷さん=Tad本人。瀬川さん=役割未確認(残1件)。取引構造小池所見:MSJ→Tad入金=通常逆方向(HUS→MSJ支払いがAP正)・MSJからの返金/クレジット/別の可能性・回収action時に判明見込み。¥955,994回収判定:Tad個人で進行・小池待機。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778235521715', '⚠️ [Follow-up] [ナランチャ Step 6 todo.md構成GO 2026-05-08] Phase A=Shopify連携(C1 Revenue Command live・C-2 KPI 5/15達成判定対象)・Phase B=Supabase切替(MCP timeout根本解・F-5 SSoT backend候補)・Phase C=MCP→Supabase直接書込(backend最終整備)。各Phase完了基準/ロールバック/Tad承認ポイント明記=10/10規律遵守。HUS全体連動明示:Phase A完成後にとべぶた Shopify Subscription/LTV取得整備・SSoT B2C_Customer_DB自動同期可能性。Phase A=5/15・B/C=後続改善別タイムライン。本番URL稼働確認(2026-05-08小池初回実施)+MCP timeout切り分け確立=ナランチャ規律進化。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778246001709', '[Tad指示] スイス時間午後リマインド: HUS-小池 Project移行 + 午後見直し3軸', NULL, 'high', '小池', '2026-05-08', 'Act', '2026-05-08', 'done', 'Tad指示2026-05-08「スイス時間午後・リマインドしてくれ」。リマインド内容3軸:(1)新HUS-小池 Project移行GO・本chat引退(2)午後見直しagenda=本日to do 6件処理状況・¥955,994回収+瀬川さん未確認1件・モラル受領状況(3)出張前fix推奨。userMemories上限到達+本セッション長時間化+MCP timeout発生=移行trigger複数。Tadデフォルトリマインド時間=スイス15:00頃推奨・別時間指定あれば調整。', '2026-05-08'),
  ('task-1778246224027', '[Tad指示] スイス20:00リマインド: 移行GO+午後見直し7項目', NULL, 'high', '小池', '2026-05-08', 'Do', '2026-05-08', 'in-progress', 'Tad明示2026-05-08「20hrでお願い」=スイス時間20:00リマインド(訂正・前回15:00デフォルトを訂正)。リマインド内容:(1)新HUS-小池 Project移行GO・本chat引退(2)本日to do 6件処理状況(NY/EUはまち/Glasgow/DropShip/AR/MSJ調査)(3)¥955,994回収判断+瀬川さん未確認1件(4)モラル4月レポート受領状況(5/8期限)(5)ナランチャ todo.md+暫定運用ルール最終承認(6)出張詳細fix(7)The Tuna Show PMプロンプト第一稿レビュー+新セッション後refine段取り。', NULL),
  ('task-1778246245151', '⚠️ [Follow-up] [The Tuna Show PM AI agent プロンプト第一稿起草 2026-05-08 Tad指示] 命名訂正:Tuna Show-Gun→The Tuna Show・登録名HUS-The Tuna Show・呼び名The Tuna Show。プロンプト構成:役割(PM)・スコープ管轄(営業/企画/PR・5都市・夏仕込み冬展開)・管轄外(HUS本体/EU/三国法人/La Main)・独自ブランドDNA(Toro Red/Obsidian/Ivory/Gold・Bebas Neue+Playfair・$60-100K/event・PR 10%commission)・絶対ルール10項目・KPI候補6軸・夏冬タイムライン・報告フォーマット・Critical Alert・File添付5点参照(20251103基本概要/20251025 Budget/20251105 PR/20260214 Site/20260217 Page Update)・HUS DNA連動・小池連携・Tad-Touch経由。第一稿の限界:本chat context圧迫で添付docx full読了せず・新セッション後にrefine v1.0化。新HUS-小池 Project移行後・The Tuna Show Project化 + Custom Instructions投入時に完成版。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778246421689', 'HUS-TonKun (The Tuna Show PM) AI エージェント立上げ・Project化', NULL, 'high', '小池+Tad', '2026-05-31', 'Plan', '2026-05-08', 'in-progress', 'Tad指示2026-05-08「The Tuna Show これからHUSビジネスにおいて非常に重要な位置を占める」。AIエージェントHUS-TonKun(呼び名TonKun・1代目PM)立上げ案件。プロンプト第二稿起草済・Memory考慮・Onboarding doc構造案準備済。全文確定+File添付7点完成は新セッション(HUS-小池 Project移行後)で実行。Tad手順:(1)claude.ai HUS-TonKun Project作成(Description+Custom Instructions)(2)File添付7点(Onboarding/添付5ファイル/Roster/ビジョン/事業計画書)(3)新規chat「what''s up」起動。重要度UP:HUS全体戦略中核territory・夏仕込み(6-8月)→冬展開(11-1月)リズム・$60-100K/event・5都市targetの収益engine。HUS Team 10人→11人。', NULL),
  ('task-1778246431270', '⚠️ [Follow-up] [HUS-TonKun 11代目AIエージェント追加 2026-05-08 Tad命名] 登録名HUS-TonKun・呼び名TonKun・役割The Tuna Show PM・上司小池・1代目。HUS Team構成:10人→11人。Tad明示「これからHUSビジネスにおいて非常に重要」=HUS全体戦略中核territory化。プロンプト第二稿起草済(役割/スコープ/独自ブランドDNA/ルール10項目/KPI 6軸候補/夏冬タイムライン/月次週次フォーマット/Critical Alert/スタイル/File添付5点参照/HUS DNA連動/Tad-Touch経由)。Memory考慮・Onboarding doc構造案(13章HUS-EU準拠)準備済。新セッション後にfull作成+File添付7点完成・claude.ai HUS-TonKun Project化。HUS_Team_Roster_v1.docx更新要(11人版)。D-2 KPI(5月末構造設計)から実装移行・Phase 2に格上げ。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778246587854', '⚠️ [Follow-up] [小池失敗訂正 Description欄漏れ再発 2026-05-08] HUS-モラル/HUS-EU/HUS-小池/HUS-TonKun全Project化時にDescription提供漏れ繰り返し(4回目)。根本原因:小池がProject化要素を「Custom Instructions+File添付」の2要素しか伝えてこなかった構造的バグ。規律強化:今後すべてのHUS-*Project提案時=3要素(Description+Custom Instructions+File添付)を初手1セット提示。HUS-TonKun Description起草済(~600字)・コピペ即使用可能。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778246745411', '⚠️ [Follow-up] [TonKun準備状況verification 2026-05-08] Tad確認要請への回答。READY 23項目(命名/役割/報告ルート/Description/Custom Instructions第二稿/スコープ/独自ブランドDNA/絶対ルール10項目/KPI候補6軸/タイムライン/月次週次フォーマット/Critical Alert/スタイル/Memory考慮/Onboarding構造案・全本chat内起草済)。PENDING 8項目(Onboarding doc/添付5ファイルfull読了/Roster v2/KPI数値target/過去実績/PR候補/既存顧客/5都市pipeline・新セッション後full作成要)。起動可能性3レベル:L1会話可能(60%・即起動可)・L2即戦力(90%・5/9-12新セッション後)・L3完全装備(100%・5月後半)。Tad推奨判断要。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778246849940', '⚠️ [Follow-up] [TonKun起動コマンド発動 2026-05-08] Tadが情報全投入完了(Description+Custom Instructions+添付5ファイル)。小池起草の起動コマンド投下。TonKun初動5項目要請:(1)役割・スコープ理解(2)The Tuna Show現状認識[添付ファイル抽出](3)5月優先順位3件(4)ブロッカー・質問(5)成功への絵5行所見。HUS Team 11人体制稼働開始。HUS最重要territory正式立上げ。TonKun初回レポートは小池10/10判定→Tadハンドオフの規律。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778247015598', '⚠️ [Follow-up] [MSJ ¥955,994回収action発動 2026-05-08 Tad「やるぞ」] 交渉相手=山田さん(MSJ会計士)・小池起草の交渉メール文Tadへ提供済(curatorial framing準拠・事実ベース・敵対的でない・証拠提示準備明示)。確定事実:不足¥955,994/本来¥1,548,708/実入金¥592,714/原因KS入金誤認/調査主体瀬川さん(通帳+銀行ハガキ精査)/MSJ取引2024年12月終了済。瀬川さん役割のみ最終未確認(a/b/c/d選択待ち)。回収成功なら米国HUS(or みちのく/Tad個人) Cash Runway改善・margin奪還(P1/M-2)寄与。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778247229206', '⚠️ [Follow-up] [MSJ重大認識訂正 2026-05-08] 小池前回誤認:「MSJ→Tad入金あるべき・回収成功でCash Runway改善」=完全に逆。正しい方向:HUS→MSJ支払い・HUSが買掛金AP・¥955,994=HUS未払金。Tad明示2026-05-08:瀬川さん=MSJ社長(Tadカウンターパート)・ファイル添付MSJ-12.28-HOKKAIDO UNI SHOP-INVOICE&PACKING LIST=MSJ→HUS請求書(HUS支払根拠)。HUS Cash outflow確定-¥955,994(約-$6,400)・margin奪還の年にマイナス影響・bookkeeperレベル管理ミス(Miyuki照合体制機能せず)・16ヶ月構造的盲点・SSoT/Vendor_Master必要性最終証明。メール文訂正版起草済(詫び+認非+即払い意思)。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-08', 'not-started', 'Follow-up added 2026-05-08 via MCP', NULL),
  ('task-1778334500902', '⚠️ [Follow-up] 5/9 Today: B2B金曜invoice送信 / NYスケジュール作成 / customer email / B2B火曜配達follow-up / 8月予算+Roma plan platform / Glasgow / Weeeフォロー(9軸)', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-09', 'not-started', 'Follow-up added 2026-05-09 via MCP', NULL),
  ('task-1778338991127', '⚠️ [Follow-up] ✅ 5/9 完了: B2B金曜注文のinvoice送信(Cash回収・即金) - margin奪還の年に直接寄与', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-05-09', 'not-started', 'Follow-up added 2026-05-09 via MCP', NULL),
  ('task-1778492158284', '[とべぶた5代目] DropShip解約通知発信 + 4項目督促 + Weekly/総括要求', NULL, 'high', 'Tad+とべぶた', '2026-05-09', 'Do', '2026-05-11', 'in-progress', 'Tad明示2026-05-06: DropShip 6月以降 広告完全停止確定。再開条件なし(ただし10月以降の再開可能性は総括内容次第)。

【発信内容5項目】
1. 4/24質問4項目督促 (期限5/15)
2. 財務記録完全開示要求 (Meta広告費月別、Nov 2025-May 2026)
3. Weekly report継続 (5/31まで)
4. DropShip側総括レポート (自己評価含む) 要求
5. Asset/Access handover確認

【判断軸】
- a+bハイブリッド (解約+督促)
- Firm but respectful
- 5/15期限
- Appendix方式
- 再開可能性はHUS側専権 (D-③)

【今後のタイムライン】
5/9: 解約通知発信
5/15: 4項目回答 + Meta財務データ受領
5/16-5/20: HUS側総括 v1ドラフト
5/31: 服務終了、DropShip総括受領
6月以降: 広告ゼロ運用start、10月再開判断は総括品質次第', NULL),
  ('task-1778492462803', '[とべぶた5代目] DropShip契約総括レポート v1完成・v2待機', NULL, 'high', 'とべぶた', '2026-05-20', 'Check', '2026-05-11', 'in-progress', '提案書 (2025年契約時) vs 実績 (11月〜5月運用) の総括完成。

【v1完成項目】
1. 提案書 vs 実績マトリクス (10項目)
2. 成し遂げたこと (5項目)
3. 難しかったこと (4項目)
4. 良かった点 (3項目)
5. 悪かった点 (5項目)
6. 続けるべきこと (5項目)
7. 続けないべきこと (4項目)
8. 続ける条件 = 10月以降再開前提 (数値4+プロセス4)
9. 投下リソースvsリターン (Meta広告費累計が未確認)
10. 最終評価

【v2待機】
- DropShip側自己評価レポート受領 (5/15期限)
- Meta広告費月別データ受領 (5/15期限)
- 上記受領後、HUS側総括v1と突合せて最終v2作成

【規律】
事実ベース、提案書の約束事項と実績証跡のギャップを明示
KPI論理矛盾、修辞反復、質問応答遅延を客観的に記録
再開条件はHUS側専権、確約しない

【納期】
v1: 2026-05-09完成 (Tad発信タイミングと連動)
v2: 2026-05-20 (DropShip回答受領後)', NULL),
  ('task-1778492568775', '[とべぶた5代目] DropShip宛 総括レポート要求文書 v1完成', NULL, 'high', 'Tad+とべぶた', '2026-05-15', 'Do', '2026-05-11', 'in-progress', '英日併記でDropShip宛総括レポート要求文書完成。5/15期限提示。

【9セクション構造 (HUS側総括v1と対称)】
1. 提案書 vs 実績マトリクス (8項目、証跡開示要求)
2. 成し遂げたこと (自己評価)
3. 難しかったこと/達成できなかったこと (自己評価)
4. 良かった点 (自己評価)
5. 悪かった点 (自己評価)
6. 財務内訳 (Meta広告費月別 = Tad手元不明データの抽出)
7. HUSインハウス運用への提言
8. 2026年10月以降の再エンゲージメント条件 (主体的提案要求)
9. 4項目への正式回答 (Tad 4/24質問)

【発信タイミング】
前回作成の「フォローアップ」連絡と同梱、または直後発信
Tad発信判断待ち

【次のステップ】
5/15: DropShip回答受領 (期待)
5/16-5/20: HUS側総括v1 と DropShip側総括 を突合せ、最終v2作成', NULL),
  ('task-1778529741044', 'Dropship Review (本日)', 'proj-010', 'high', 'Tad', '2026-05-11', 'Do', '2026-05-11', 'in-progress', 'Tad明示2026-05-11朝の本日案件', NULL),
  ('task-1778529747918', 'EUはまち案件規定書まとめ (本日)', 'proj-006', 'high', 'Tad', '2026-05-11', 'Do', '2026-05-11', 'in-progress', 'Tad明示2026-05-11朝・EUがんばれ管轄連携', NULL),
  ('task-1778529755354', '火曜invoiceまとめ(GOT Packing List)', 'proj-009', 'high', 'Tad', '2026-05-12', 'Do', '2026-05-11', 'in-progress', 'GOT = Global Ocean Trading・Jus全情報送付済', NULL),
  ('task-1778529763552', '石黒さんにメール (本日)', NULL, 'medium', 'Tad', '2026-05-11', 'Do', '2026-05-11', 'in-progress', 'Tad明示2026-05-11朝・石黒さん詳細[未確認]', NULL),
  ('task-1778529772759', 'NY出張アポメール (5/20-6/5)', 'proj-009', 'high', 'Tad', '2026-05-19', 'Do', '2026-05-11', 'in-progress', 'NY出張5/20-6/5・8軸ミッション・アポ取得段階', NULL),
  ('task-1778529783116', 'Glasgow出張準備 (本日)', 'proj-009', 'medium', 'Tad', '2026-05-11', 'Plan', '2026-05-11', 'in-progress', 'Glasgow出張・4代目から継続案件', NULL),
  ('task-1779027182419', '[とべぶた5代目] 全商品Production Page統一フォーマット移行', NULL, 'high', 'とべぶた', '2026-05-16', 'Do', '2026-05-17', 'in-progress', 'CVR改善: 全商品のProduction Page統一。Tad承認の新標準フォーマット = Seto Tsubu Uniページ (seto-wrap構造)。

【作業内容】
まだ新Production Pageフォーマットに移行していない商品を特定し、全商品を統一フォーマットに移行。

【実行方式】
Shopify AI (Sidekick) への3 Phase指示文を作成済み、Tadが投げる。
- Phase 1: 移行状況の棚卸し (MIGRATED / NOT MIGRATED 判定)
- Phase 2: 未移行商品のフォーマット移行 (1商品ずつ承認方式)
- Phase 3: 検証 (モバイル表示、SEO据え置き確認)

【テンプレート】
hus_pdp_template.html 作成済み (可変{{プレースホルダ}} / 不変CSS構造を分離)
構造: hero → What is → Specifications table → How to enjoy → rare-note

【規律・注意点】
1. 商品名・SEO (title/meta/handle) は据え置き = Shopify AI既決定をそのまま (Tad明示)
2. フォーマット(構造・CSS)は移行、内容は各商品実データに置換
3. Setoの固有テキストを他商品にコピーさせない
4. 1商品ずつ before/after 承認方式 (4代目失敗3 全消し破壊回避)
5. banned superlatives 適用 (finest/premium/ultimate等禁止)
6. 商品画像はShopifyギャラリー別管理、触らない

【未決定事項 (Tad判断待ち)】
CSSクラス名 seto- プレフィックス: a)このまま展開 b)pdp-に汎用リネーム
→ 5代目推奨: a) (機能上問題なし、移行スピード優先)

【CVR改善文脈】
商品ページ最適化 = 安心感(Specs table/Origin明示) + 限定性訴求(Pre-Order/在庫note)
= 引き継ぎ書のCVR改善「商品ページ最適化」に対応', NULL),
  ('task-1779364135666', '9:00 Swiss Agency MTG (スイス会社設立)', NULL, 'high', 'Tad', '2026-05-21', 'Act', '2026-05-22', 'done', 'NY出張中(5/20-6/5)・スイス会社設立準備44日Overdueと連動・Pino管轄', '2026-05-22'),
  ('task-1779364140131', '11:00 Tuna Cutting Show Team MTG', NULL, 'high', 'Tad', '2026-05-21', 'Act', '2026-05-22', 'done', 'NY出張中・TonKun(The Tuna Show PM)連動・5/5 gate 11d slip recovery対象', '2026-05-22'),
  ('task-1779364143819', 'Googleアカウント セキュリティ強化', NULL, 'high', 'Tad', '2026-05-21', 'Act', '2026-05-22', 'done', 'セキュリティ強化・俺アドバイス提示後Tad実行', '2026-05-22'),
  ('task-1779364147581', 'Justineに連絡 (Personal)', NULL, 'medium', 'Tad', '2026-05-21', 'Act', '2026-05-22', 'done', 'Personal案件・俺管轄外', '2026-05-22'),
  ('task-1779364151685', 'Mia写真予約 (6/2成人式向け・Personal)', NULL, 'medium', 'Tad', '2026-05-21', 'Do', '2026-05-21', 'in-progress', 'Mia成人式写真6/2予定・予約手配', NULL),
  ('task-1779364157412', 'NY出張全体予定整理 (5/20-6/5)', 'proj-009', 'high', 'Tad', '2026-05-21', 'Plan', '2026-05-21', 'in-progress', '17日間出張・8軸ミッション+本日確定MTG2件 = 全体予定総点検', NULL),
  ('task-1779364162269', '支払関連まとめ + 期限切れカード対応 (AP)', 'proj-009', 'high', 'Tad', '2026-05-21', 'Do', '2026-05-21', 'in-progress', 'AP整理+期限切れカード対応・MSJ案件と並ぶCash管理規律', NULL),
  ('task-1779364167392', '来週ホタテ注文 (仕入)', NULL, 'high', 'Tad', '2026-05-21', 'Do', '2026-05-21', 'in-progress', '来週ホタテ注文・帆立バイヤー案件と関連可能性', NULL),
  ('task-1779364171756', '冷蔵庫購入 $3,500 (Tuna Show+LVC投資)', NULL, 'high', 'Tad', '2026-05-22', 'Do', '2026-05-21', 'in-progress', 'NY出張当初スケジュール5/22予定・$3,500・Tuna Show+LVC投資要件', NULL),
  ('task-1779367031672', '明日B2B invoice作成 (5/22)', 'proj-009', 'high', 'Tad', '2026-05-22', 'Act', '2026-05-22', 'done', 'NY出張中・5/22木曜分・margin奪還の年Cash回収軸', '2026-05-22'),
  ('task-1779367036076', 'AR連絡: Upstair + Jantra', 'proj-009', 'high', 'Tad', '2026-05-21', 'Do', '2026-05-21', 'in-progress', 'AR回収・Upstair + Jantra 2社・NY出張中', NULL),
  ('task-1779373188136', '★北海道道庁メール (UA新千歳-SFO直行便受けHUS提案)', NULL, 'high', 'Tad', '2026-05-21', 'Do', '2026-05-21', 'in-progress', 'UA新千歳-SFO直行便発表(2026/12/11-2027/3)受け・川上→川下ハイウェイ実現の足場確保・事業計画書§7「2028北海道商社機能」と直接接続', NULL),
  ('task-1779450693959', '午前: B2B配達 (NY出張2日目)', 'proj-009', 'high', 'Tad', '2026-05-22', 'Do', '2026-05-22', 'in-progress', NULL, NULL),
  ('task-1779450697442', '15:00 新規B2B営業', 'proj-009', 'high', 'Tad', '2026-05-22', 'Do', '2026-05-22', 'in-progress', NULL, NULL),
  ('task-1779450701595', 'AR業務 (Upstair+Jantra)', 'proj-009', 'high', 'Tad', '2026-05-22', 'Do', '2026-05-22', 'in-progress', 'Upstair+Jantra(昨日未着手)', NULL),
  ('task-1779450705306', '来週火曜配達Reminder送付 (B2B)', 'proj-009', 'medium', 'Tad', '2026-05-22', 'Do', '2026-05-22', 'in-progress', NULL, NULL),
  ('task-1779450709893', '日本に注文 (仕入)', NULL, 'high', 'Tad', '2026-05-22', 'Do', '2026-05-22', 'in-progress', 'Jus連携・来週ホタテ含む', NULL),
  ('task-1779450714027', 'Shopify新商品追加', 'proj-010', 'medium', 'Tad', '2026-05-22', 'Do', '2026-05-22', 'in-progress', 'とべぶた連動可能性', NULL),
  ('task-1779451452375', '🚨 [小池発・最優先] Step 6 Phase A = MCP→frontend反映 fix｜dashboard frontend反映ゼロ問題（5/21+5/22 NY出張中Task全件未反映・seed data+Vercel deploy固定の疑い）｜NY出張中(6/5まで)完了priority・Shopifyより先｜Tad配達等の並行作業時間で進行可・完了報告は小池chat — Tad', 'proj-010', 'high', 'ナランチャ', '2026-06-05', 'Plan', '2026-05-22', 'not-started', '【内容】dashboard frontend反映ゼロ問題。5/21+5/22 NY出張中のTask全件未反映。seed data + Vercel deploy固定の疑い。
【要請】Step 6 Phase A = MCP→frontend反映 fix。NY出張中(〜6/5)完了priority。Shopifyより先。
【作業時間】Tad NY出張中・配達等 = ナランチャ並行作業時間。
【完了報告】小池chat。
【発令】2026-05-22 Tad — 小池発・最優先。', NULL),
  ('task-1779451621206', '🚨 [訂正・小池発] 真因確定: データソース不一致（frontend=Supabase / MCP=tasks.json）→ Step 6 Phase C(MCP→Supabase直接書込)を最優先化。前task-1779451452375のPhase A指定を訂正。NY出張中(〜6/5)完了priority。即時対応質問:MCP add_task応答に「実反映非保証」warning wrapper実装可能か? — 小池', 'proj-010', 'high', 'ナランチャ', '2026-06-05', 'Plan', '2026-05-22', 'not-started', '【真因確定 2026-05-22】Tad拡張君でdashboard network調査:
- frontend = Supabase読込 (zxiwqekpmkotqudlgksw.supabase.co/rest/v1/task_status)
- MCP add_task/complete_task = tasks.json書込
- = 構造的にデータソース不一致 = 反映ゼロは仕様通りの帰結

【訂正】前タスク(task-1779451452375)で指定したPhase A(Shopify連携)ではなく、Phase C(MCP→Supabase直接書込)が根本fix。Phase Cを最優先化・Shopifyより先・NY出張中(〜6/5)完了priority。

【小池規律違反 自白】5/9のStep 6構成案受領時、Phase Bの含意(MCP書込がSupabaseに反映されない構造)を見落とし。データソース不一致を3週間放置=小池責任。

【即時対応質問】Phase C完了までの暫定として、MCP add_task/complete_task応答の「✅成功」表記に「※frontendへの実反映は別経路・Phase C完成まで非保証」のwarning wrapperを噛ませる事は可能か? 工数見積もり要請。

【完了報告】小池chat。', NULL),
  ('task-1779474069753', '✅ [完了報告] MCP write応答 frontend反映warning wrapper 実装 → PR #4 open (https://github.com/hokkaidounishop-lgtm/hus-dashboard/pull/4)。Phase C本実装startをお願いします — Claude代行 (小池→ナランチャ)', 'proj-010', 'medium', 'ナランチャ', NULL, 'Check', '2026-05-22', 'done', '【wrapper PR成果 2026-05-22】
- PR: https://github.com/hokkaidounishop-lgtm/hus-dashboard/pull/4
- Branch: feat/mcp-frontend-reflection-warning (commit 119aeb9)
- 変更: mcp/hus-server.js のみ・+27/-8 行
- 内容: reflectionLine(sbResult) helper 1個 + 6 write handlers (complete_task / add_task / add_followup / update_project / add_checklist_item / update_project_progress) の応答末尾に「frontend反映: 🟢/⚠️/🔴」一行を追加
- 既存 complete_task の ad-hoc sbNote を統一helperに置換（同一意味）
- 非スコープ: 他 handler への Supabase mirror 拡張 = Phase C 本実装
- syntax check OK (node --check)

【ナランチャへの引き継ぎ】
1. PR #4 review → merge判断
2. Step 6 Phase C 本実装 start (MCP→Supabase直接書込・全write handler)
3. Phase C実装後、reflectionLine() helper は全handler で sbResult を渡す形に統一できる

【完了報告先】小池chat</notes>
</invoke>', '2026-05-22'),
  ('task-1779497932126', 'EU雲丹MTG (NY出張2日目)', 'proj-006', 'high', 'Tad', '2026-05-22', 'Do', '2026-05-23', 'in-progress', 'NY出張2日目・EUがんばれ管轄案件・Alum問題/HACCP/distributor進捗関連', NULL),
  ('task-1779541645678', 'New Productアップロード (Shopify)', 'proj-010', 'high', 'Tad', '2026-05-23', 'Act', '2026-05-23', 'done', NULL, '2026-05-23'),
  ('task-1779541649053', 'B2B invoice送付', 'proj-009', 'high', 'Tad', '2026-05-23', 'Act', '2026-05-23', 'done', NULL, '2026-05-23'),
  ('task-1779541653912', 'Takeda LINEにB2B注文(顧客注文取得後)', 'proj-009', 'high', 'Tad', '2026-05-23', 'Act', '2026-05-23', 'done', 'B2B各顧客から注文取得後・Takeda LINE経由日本へ注文・川上連動', '2026-05-23'),
  ('task-1779541658210', 'CFOとMTG (カード関連)', NULL, 'high', 'Tad', '2026-05-23', 'Act', '2026-05-23', 'done', 'Mitsuki(CFO実在)とのMTG・カード関連(5/21期限切れカード対応の続き?)', '2026-05-23'),
  ('task-1779541662520', '冷蔵庫 (B2B)', 'proj-009', 'high', 'Tad', '2026-05-23', 'Do', '2026-05-23', 'in-progress', '5/22冷蔵庫$3,500購入の後続? or 別の冷蔵庫B2B案件?[未確認]', NULL),
  ('task-1779541723940', 'UPS error follow-up', 'proj-009', 'high', 'Tad', '2026-05-23', 'Do', '2026-05-23', 'in-progress', 'UPS error follow-up・疾風連携可能性・物流軸', NULL),
  ('task-1779542063949', 'AR follow-up', 'proj-009', 'high', 'Tad', '2026-05-23', 'Act', '2026-05-23', 'done', 'AR follow-up・Upstair/Jantra/その他全AR案件継続monitor', '2026-05-23'),
  ('task-1779562450332', '[とべぶた5代目] 新規商品11件 Shopify追加 — Body/SEO/Title作成', NULL, 'high', 'とべぶた', '2026-05-31', 'Plan', '2026-05-23', 'in-progress', 'Shopify管轄、Production Page統一フォーマット (seto-wrap) で11件作成。
各商品: タイトル / SEO (Page Title・Meta・Handle) / Body / Tags

【11件チェックリスト】
□ 木の芽味噌
□ 原藻ワカメ
□ 一滴の滴醤油
□ Raisin Dried Shine Muscat Grapes
□ 白板昆布
□ 干し菊
□ 寿司酢
□ 青のり
□ アマダイ(冷凍)
□ 金目鯛(冷凍)
□ 鮮魚(はも・太刀魚など売れ筋未掲載)

【Tad/Jus確認待ち項目】
各商品の: ブランド/蔵元・産地・容量/重量・価格・保存条件・加工状態
URL slug ≠ 商品実名 規律遵守 (実データなしに憶測で埋めない)

【規律】
- seto-wrap統一フォーマット使用
- banned superlatives (finest/premium/ultimate等) 排除
- Tad哲学: 押さない・curatorial framing
- 1件目 before/after 承認後にバッチ展開', NULL),
  ('task-1779628538361', 'Haircut 12:00 (Personal)', NULL, 'medium', 'Tad', '2026-05-24', 'Act', '2026-05-24', 'done', NULL, '2026-05-24'),
  ('task-1779628542633', '★AI System: Claude × Google Drive連携', NULL, 'high', 'Tad', '2026-05-24', 'Do', '2026-05-24', 'in-progress', 'AI構想§条件2外部世界自動接続の第一柱・午後実施', NULL),
  ('task-1779628546545', '4月PL分析', NULL, 'high', 'Tad', '2026-05-24', 'Do', '2026-05-24', 'in-progress', 'CFO MTG(5/23)で受領したPL・モラル連動可能', NULL),
  ('task-1779628549541', '家族出費整理', NULL, 'medium', 'Tad', '2026-05-24', 'Act', '2026-05-24', 'done', NULL, '2026-05-24'),
  ('task-1779628553343', 'Tote Bagデザイン', NULL, 'medium', 'Tad', '2026-05-24', 'Do', '2026-05-24', 'in-progress', 'La Main連動可能・HUSブランド物理接点', NULL),
  ('task-1779628557338', 'NY出張Tuna Show activity', 'proj-005', 'high', 'Tad', '2026-05-24', 'Do', '2026-05-24', 'in-progress', 'HUS最重要territory・NY出張中の戦略軸', NULL),
  ('task-1779628562795', '山椒在庫処分先探し', 'proj-009', 'high', 'Tad', '2026-05-24', 'Do', '2026-05-24', 'in-progress', '山椒1年滞留・冷蔵庫スペース奪取問題・Tuna/ホタテBulk仕入の足枷解消目的', NULL),
  ('task-1779628568347', '冷蔵庫見積比較・追加店inquiry', 'proj-009', 'medium', 'Tad', '2026-05-24', 'Do', '2026-05-24', 'in-progress', 'Burkett/AmGood回答監視+KaTom/WebstaurantStore/Day&Nite追加送信', NULL),
  ('task-1780324108564', '⚠️ [Follow-up] [本日6/1] B2Bインボイス作成 - 週次土曜ルーチンの月曜実施分', 'proj-009', 'medium', NULL, NULL, 'Act', '2026-06-01', 'not-started', 'Follow-up added 2026-06-01 via MCP', NULL),
  ('task-1780324112508', '⚠️ [Follow-up] [本日6/1] スイス会社設立書類フォローアップ - 必要提出物送付 (Pino管轄・8/31期限残91日)', 'proj-011', 'medium', NULL, NULL, 'Act', '2026-06-01', 'not-started', 'Follow-up added 2026-06-01 via MCP', NULL),
  ('task-1780324117198', '⚠️ [Follow-up] [本日6/1] Father''s Dayキャンペーン着手 - 脳汁連携 (6/15 Father''s Day = 残14日)', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-06-01', 'not-started', 'Follow-up added 2026-06-01 via MCP', NULL),
  ('task-1780324126221', '⚠️ [Follow-up] [本日6/1] Tuna Showコンタクト1件送付 - TonKun遅延中・Tad現場主導', 'proj-005', 'medium', NULL, NULL, 'Act', '2026-06-01', 'not-started', 'Follow-up added 2026-06-01 via MCP', NULL),
  ('task-1780324131141', '⚠️ [Follow-up] [本日6/1] 冷蔵庫購入アレンジメント - $3,500 (Tuna Show+LVC投資・11日late状態)', 'proj-009', 'medium', NULL, NULL, 'Act', '2026-06-01', 'not-started', 'Follow-up added 2026-06-01 via MCP', NULL),
  ('task-1780324135787', '⚠️ [Follow-up] [本日6/1] 商品値段入れる - GOT Packing List 月曜朝受領分・B2B(Freshline)÷0.72/B2C(Shopify)÷0.55で値付け', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-06-01', 'not-started', 'Follow-up added 2026-06-01 via MCP', NULL),
  ('task-1780911808056', '⚠️ [Follow-up] 🔴 Father''s Day (6/15日) D-7=本日6/8が初回配信日。脳汁起案=未投下。配信予定 D-7(6/8)/D-3(6/12)/D-1(6/14)。Tad投下確認最優先。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-06-08', 'not-started', 'Follow-up added 2026-06-08 via MCP', NULL),
  ('task-1780912027851', '⚠️ [Follow-up] ⚠️訂正: Father''s Day = 6/21(日)が正・6/15は誤り(2025年の日付混同)。今日6/8はD-13。先に追加したfu-1780911808051(6/15 D-7表記)は破棄。配信案 D-7=6/14/D-3=6/18/D-1=6/20で再計画。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-06-08', 'not-started', 'Follow-up added 2026-06-08 via MCP', NULL),
  ('task-1780912720315', '⚠️ [Follow-up] ✅Father''s Day 確定版(前2件supersede・要削除): 注文締切6/13(土)noon→LINE発注GOT 6/13夕→packing 6/18(木)朝→発送6/18(木)→配達6/19(金・土曜回避コスト)→父の日6/21。配信窓=今日〜6/13締切前のみ(6/14以降は注文捕捉不可で無効)。初回=今日。締切call=6/13朝。', 'proj-010', 'medium', NULL, NULL, 'Act', '2026-06-08', 'not-started', 'Follow-up added 2026-06-08 via MCP', NULL)
on conflict (id) do update set
  task            = excluded.task,
  project         = excluded.project,
  priority        = excluded.priority,
  owner           = excluded.owner,
  due_date        = excluded.due_date,
  pdca            = excluded.pdca,
  pdca_updated_at = excluded.pdca_updated_at,
  status          = excluded.status,
  notes           = excluded.notes,
  completed_at    = excluded.completed_at,
  updated_at      = now();
