#!/usr/bin/env python3
"""
Generate supabase/projects_table.sql — the one-paste migration that makes
Supabase the single source of truth for the dashboard project list, mirroring
what tasks_table.sql did for tasks.

It creates `public.projects` (full project rows: scalar fields as columns,
nested `blocks` / `followups` as jsonb), enables RLS with anon read/write
(matching the tasks table convention), and seeds it with the CURRENT board
state from src/data/projects.json so nothing is lost in the cutover.

Run:  python3 scripts/gen_projects_seed.py
Then paste the generated supabase/projects_table.sql into the Supabase SQL editor.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
projects = json.load(open(os.path.join(ROOT, "src/data/projects.json")))


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def sql_int(v):
    if v is None or v == "":
        return "NULL"
    return str(int(v))


def sql_jsonb(v):
    # Compact JSON, single-quote-escaped, cast to jsonb. Default to [] so the
    # column is never NULL (frontend/MCP always get an array to map over).
    payload = json.dumps(v if v is not None else [], ensure_ascii=False)
    return "'" + payload.replace("'", "''") + "'::jsonb"


COLS = ["id", "name", "description", "status", "owner", "kpis", "deliverables",
        "start_date", "due_date", "progress", "blocks", "followups", "notes"]


def row_values(p):
    return [
        sql_str(p.get("id")),
        sql_str(p.get("name")),
        sql_str(p.get("description")),
        sql_str(p.get("status")),
        sql_str(p.get("owner")),
        sql_str(p.get("kpis")),
        sql_str(p.get("deliverables")),
        sql_str(p.get("startDate")),
        sql_str(p.get("dueDate")),
        sql_int(p.get("progress")),
        sql_jsonb(p.get("blocks")),
        sql_jsonb(p.get("followups")),
        sql_str(p.get("notes")),
    ]


lines = []
lines.append("""-- HUS Dashboard — `projects` table: Supabase as single source of truth.
-- Run ONCE in the Supabase SQL editor for the hus-dashboard project.
--
-- Why: project rows lived only in build-time projects.json. MCP edits
-- (update_project / add_checklist_item / add_followup / progress recalc) and
-- frontend edits never met — same divergence the `tasks` table fixed. This
-- table holds the FULL project rows (scalars as columns, nested blocks /
-- followups as jsonb) so MCP writes and frontend edits share one live source.
--
-- Generated by scripts/gen_projects_seed.py — do not hand-edit the seed block.

create table if not exists projects (
  id           text primary key,
  name         text,
  description  text,
  status       text,
  owner        text,
  kpis         text,
  deliverables text,
  start_date   text,
  due_date     text,
  progress     integer,
  blocks       jsonb        not null default '[]'::jsonb,
  followups    jsonb        not null default '[]'::jsonb,
  notes        text,
  deleted      boolean      not null default false,
  updated_at   timestamptz  not null default now()
);

alter table projects enable row level security;

-- The dashboard uses the public anon key; RLS is what protects the data.
drop policy if exists "anon read projects"   on projects;
drop policy if exists "anon write projects"  on projects;
drop policy if exists "anon update projects" on projects;
create policy "anon read projects"   on projects for select to anon using (true);
create policy "anon write projects"  on projects for insert to anon with check (true);
create policy "anon update projects" on projects for update to anon using (true) with check (true);

-- ── Seed: current board state (projects.json) ──""")

lines.append("insert into projects (" + ", ".join(COLS) + ") values")
rows = []
for p in projects:
    rows.append("  (" + ", ".join(row_values(p)) + ")")
lines.append(",\n".join(rows))
lines.append("""on conflict (id) do update set
  name         = excluded.name,
  description  = excluded.description,
  status       = excluded.status,
  owner        = excluded.owner,
  kpis         = excluded.kpis,
  deliverables = excluded.deliverables,
  start_date   = excluded.start_date,
  due_date     = excluded.due_date,
  progress     = excluded.progress,
  blocks       = excluded.blocks,
  followups    = excluded.followups,
  notes        = excluded.notes,
  updated_at   = now();""")

out = os.path.join(ROOT, "supabase/projects_table.sql")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out} ({len(projects)} projects)")
