#!/usr/bin/env python3
"""
Generate supabase/tasks_table.sql — the one-paste migration that makes Supabase
the single source of truth for the dashboard task list.

It creates `public.tasks` (full task rows, not just a status overlay), enables
RLS with anon read/write (matching revenue_manual / morning_* convention), and
seeds it with the CURRENT board state: tasks.json (213 rows) with the live
task_status overlay (17 rows) applied, so no completion is lost in the cutover.

Run:  python3 scripts/gen_tasks_seed.py
Then paste the generated supabase/tasks_table.sql into the Supabase SQL editor.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tasks = json.load(open(os.path.join(ROOT, "src/data/tasks.json")))
overlay_rows = json.load(open("/tmp/overlay.json"))
overlay = {r["id"]: r for r in overlay_rows}

# Apply the live status overlay onto the bundled task bodies.
for t in tasks:
    o = overlay.get(t["id"])
    if not o:
        continue
    if o.get("status"):
        t["status"] = o["status"]
    if o.get("completed_at"):
        t["completedAt"] = o["completed_at"]
    if o.get("pdca"):
        t["pdca"] = o["pdca"]
    if o.get("pdca_updated_at"):
        t["pdcaUpdatedAt"] = o["pdca_updated_at"]

def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

COLS = ["id", "task", "project", "priority", "owner", "due_date",
        "pdca", "pdca_updated_at", "status", "notes", "completed_at"]

def row_values(t):
    return [
        sql_str(t.get("id")),
        sql_str(t.get("task")),
        sql_str(t.get("project")),
        sql_str(t.get("priority")),
        sql_str(t.get("owner")),
        sql_str(t.get("dueDate")),
        sql_str(t.get("pdca")),
        sql_str(t.get("pdcaUpdatedAt")),
        sql_str(t.get("status")),
        sql_str(t.get("notes")),
        sql_str(t.get("completedAt")),
    ]

lines = []
lines.append("""-- HUS Dashboard — `tasks` table: Supabase as single source of truth.
-- Run ONCE in the Supabase SQL editor for the hus-dashboard project.
--
-- Why: the frontend used to read a frozen, build-time copy of tasks.json and
-- only overlay status changes from `task_status`. New tasks added via MCP could
-- never appear, and cleanup never reflected. This table holds the FULL task
-- rows so MCP writes and frontend edits share one live source.
--
-- Generated by scripts/gen_tasks_seed.py — do not hand-edit the seed block.

create table if not exists tasks (
  id              text primary key,
  task            text,
  project         text,
  priority        text,
  owner           text,
  due_date        text,                       -- 'YYYY-MM-DD' or '' (matches tasks.json)
  pdca            text,
  pdca_updated_at text,
  status          text,
  notes           text,
  completed_at    text,
  deleted         boolean      not null default false,
  updated_at      timestamptz  not null default now()
);

alter table tasks enable row level security;

-- The dashboard uses the public anon key; RLS is what protects the data.
drop policy if exists "anon read tasks"   on tasks;
drop policy if exists "anon write tasks"  on tasks;
drop policy if exists "anon update tasks" on tasks;
create policy "anon read tasks"   on tasks for select to anon using (true);
create policy "anon write tasks"  on tasks for insert to anon with check (true);
create policy "anon update tasks" on tasks for update to anon using (true) with check (true);
""")

lines.append("-- ── Seed: current board state (tasks.json + live task_status overlay) ──")
lines.append("insert into tasks (" + ", ".join(COLS) + ") values")
value_rows = []
for t in tasks:
    value_rows.append("  (" + ", ".join(row_values(t)) + ")")
lines.append(",\n".join(value_rows))
lines.append("""on conflict (id) do update set
  task            = excluded.task,
  project         = excluded.project,
  priority        = excluded.priority,
  owner           = excluded.owner,
  due_date        = excluded.due_date,
  pdca            = excluded.pdca,
  pdca_updated_at = excluded.pdca_updated_at,
  status          = excluded.status,
  notes           = excluded.notes,
  completed_at    = excluded.completed_at,
  updated_at      = now();
""")

out = os.path.join(ROOT, "supabase/tasks_table.sql")
with open(out, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {out} — {len(tasks)} seed rows")
